- identity_core/src/common/convert/as_json.rs
- identity_core/src/common/mod.rs
This is just splitting up `AsJson` so traits can be used with more relaxed bounds
> Add FromJson/ToJson convenience traits

- identity_core/src/did/did.rs
- identity_core/src/did/did_diff.rs
- identity_core/src/did/document.rs
- identity_core/src/did/mod.rs
Adds a manual implementation of the diff trait on the DID struct to allow the method name to pass through each diff.
> Feat(core): Add manual implementation of Diff on DID. 

- libraries/wasm/package.json
> fix(wasm): Fix license identifier

- libraries/wasm/Cargo.toml
- libraries/wasm/LICENSE
- libraries/wasm/package.json
This PR just merely adds a description to the Cargo.toml, adds the LICENSE file and the dev-dep of wasm-pack.
> fix(wasm): resolve build erors and warnings

- .github/workflows/build-and-test.yml
Adds `-Append` so the env is not overwritten
> fix(ci): Avoid overwriting env on Windows

- examples/Cargo.toml
This downgrades `smol/smol-potat` dependencies used in the examples to fix compatibility issues with iota.rs
We can upgrade again or switch to using `tokio 1.0` after Chrysalis Pt.2
> Update smol/smol-potat to compatible version

- bindings/wasm/.npmignore
When `.npmignore` does not exist, NPM will use the `.gitignore` instead. Since the `web` and `node` folders are gitignored, they won't be present in the NPM package. This PR creates a `.npmignore` so that they are included.
> fix(bindings/wasm): Use npmignore so that WASM binaries are included

- identity-core/src/common/timestamp.rs
The code below was failing because `Timestamp`s had sub-second precision when created with `Timestamp::now` but changed to whole seconds when serialized as JSON. This was partly a regression from https://github.com/iotaledger/identity.rs/pull/122 - there was also a case where timestamps could be parsed directly with sub-second precision.
```rust
/// Deserializes a Document from a JSON string.
pub fn from_json(json: &String) -> Result<Document, CoreError> {
match Document::from_json(&json) {
Ok(document) => Ok(document),
Err(e) => Err(e),
}
}
/// Serializes an Document into a JSON string.
pub fn to_json(document: &Document) -> Result<String, CoreError> {
match document.to_json() {
Ok(document) => Ok(document),
Err(e) => Err(e),
}
}
/// Creates a new Document
pub fn create_did_document() -> …
```
> Ensure consistent timestamp precision

- bindings/wasm/Cargo.toml
- bindings/wasm/src/document.rs
- examples/Cargo.toml
- examples/merkle_key.rs
- identity-core/Cargo.toml
- identity-core/src/convert/json.rs
- identity-core/src/crypto/ed25519.rs
- identity-core/src/crypto/merkle_key/base.rs
- identity-core/src/crypto/merkle_key/impls.rs
- identity-core/src/crypto/merkle_key/mod.rs
- identity-core/src/crypto/merkle_key/tests.rs
- identity-core/src/crypto/merkle_key/traits.rs
- identity-core/src/crypto/merkle_tree/digest.rs
- identity-core/src/crypto/merkle_tree/merkle.rs
- identity-core/src/crypto/merkle_tree/node.rs
- identity-core/src/error.rs
- identity-core/src/utils/generate_ed25519.rs
- identity-iota/Cargo.toml
- identity-iota/src/did/url/did.rs
Part of https://github.com/iotaledger/identity.rs/issues/132 - (Update Identity.rs to use Crypto.rs)
Also closes https://github.com/iotaledger/identity.rs/issues/143 - (Blake2b256 with Merkle Key Collections)
> Use crypto.rs

- .github/workflows/build-and-test.yml
- .github/workflows/clippy.yml
- .github/workflows/format.yml
Reduces the number of GitHub actions from 34 to 6 by targeting the entire workspace (bindings are still separate).
This is an overall improvement to the speed of CI and the platform matrix now includes `macos-latest`
> Improve CI Speed

- .github/workflows/build-and-test.yml
- Cargo.toml
There's a known issue on GitHub Actions macOS runners when you cache the Rust `target` folder, specifically with `serde_derive` (https://github.com/actions/cache/issues/403). There seems to be something wrong with BSD `tar` so the Actions team included GNU `tar` with the new macOS image that was recently rolled out.  `actions/cache@v2.1.4` will use GNU tar if installed. This currently isn't released under the v2 tag as some people ran into permissions issues (https://github.com/actions/cache/issues/527), so we can pin it to this version for now.
Fixes #183 
N/A
> fix(ci): Use actions/cache v2.1.4 on workflows that run on macOS

- bindings/wasm/Cargo.toml
- identity-core/src/crypto/merkle_key/verifier.rs
- identity-core/src/crypto/proof/jcs_ed25519.rs
- identity-core/src/crypto/signature/ed25519.rs
- identity-core/src/crypto/signature/traits/core.rs
- identity-core/src/error.rs
- identity-iota/Cargo.toml
- identity-iota/src/client/client.rs
- identity-iota/src/did/doc/diff.rs
- identity-iota/src/tangle/mod.rs
Fix `DocumentDiff` signature verification - this was failing because `message_id` was included in the serialized data
Ran examples locally
> Fix diff chain

- docs/DID Communications Research and Specification/Interactions and Messages.md
Discussed in issue #187 
(Didn't realize docs/didcomms_spec wasn't deleted after last merge, hence this PR)
Adds three interactions for Verifiable Credential issuance, one for revocation, one for VP presentation.
---
The Verifiable Credential (VC) issuance flow consists of a three step interaction process between two parties, the <u>issuer</u> and the <u>holder</u>.
In the first interaction (Credential Options), the <u>holder</u> queries the <u>issuer</u> for a list of VC types that the <u>issuer</u> offers to issue.
In the second interaction (Credential Schema), the <u>holder</u> queries the <u>issuer</u> for the precise schema of one of the VCs that the <u>issuer</u> offers to issue, with it's own list of requirements which must be satisfied by the <u>holder</u> in order to qualify for …
> add credential Options, Schema, Issuance interactions, more

- README.md
- examples/create_did_document.rs
- identity-iota/src/client/network.rs
- identity-iota/src/did/doc/diff.rs
- identity-iota/src/did/doc/document.rs
- identity/README.md
Replace `Network`'s `From<DID>` trait instance with an explicit `Network::from_did()` function.
The `From` trait is usually used to convert between representationally equivalent types, in this case an explicit `from_did()` is more clear than an `.into()`.
This is an API only change, no change in functionality. Previously, one would write:
```rust
let network: Network = document.id().into();
```
After this change, one writes:
```rust
let network = Network::from_did(document.id());
```
API change only, re-built full project and examples.
> Replace Network From<DID> with from_did()

- identity-iota/src/tangle/message_index.rs
- Multiple elements with the same previous_message_id are ordered by their message_id
-  
- fixes #201
- 
- [x ] I have commented my code, particularly in hard-to-understand areas
> Fix MessageIndex determinism

- examples/diff_chain.rs
- identity-core/Cargo.toml
- identity-iota/Cargo.toml
- identity-iota/src/chain/diff.rs
- identity-iota/src/chain/document.rs
- identity-iota/src/chain/integration.rs
Renames a few AuthChain references that were missed in https://github.com/iotaledger/identity.rs/pull/230
Ran tests
> Rename AuthChain references

- identity/README.md
Update README example to use `IotaDocument` instead of `Document`. I missed updating this README in #219.
Follow-up to #219.
N/A - documentation change only
> Update README example to use IotaDocument instead of Document

- identity-iota/src/did/doc/iota_document.rs
Add `IotaDocument` unit tests for `methods()` and `controller()`.
This is in preparation to address #172, which I discovered doesn't have any unit tests that call `IotaDocument::controller()` or `IotaDocument::methods()`. These tests are relatively straightforward, but will now clearly show changes in types after returning the "correct" (aka. Iota-specific types) for these methods.
#172
`cargo test`
> Add IotaDocument unit tests for methods and controller.

- bindings/wasm/docs/api-reference.md
- bindings/wasm/examples/node.js
- bindings/wasm/examples/web.js
- bindings/wasm/package.json
- bindings/wasm/src/wasm_did.rs
- bindings/wasm/src/wasm_document.rs
- bindings/wasm/src/wasm_verification_method.rs
- Rename `WasmDocument` -> `Document`
- Rename `WasmVerificationMethod` -> `VerificationMethod`
- Update rustdoc comments to use JS types
- Ensure functions are associated with renamed JS types
Ran examples
> Rename JS types

- identity-iota/src/did/doc/diff.rs
- identity-iota/src/did/doc/properties.rs
Rename `previous_message_id` field to `previousMessageId` (camelCase) as per JSON and IOTA DID spec.
The rename was made in:
- `identity-iota/src/did/doc/diff.rs`: `DocumentDiff.previous_message_id`
- `identity-iota/src/did/doc/properties.rs`: `Properties.previous_message_id`
The in-code name remains the same (snake_case).
#222 
Previously serialized message structures will now fail to parse due to field rename.
`cargo test`
Nothing failed, maybe we should have some golden parse & structure tests 🤔
> Rename previous_message_id field to use camelCase in JSON output.

- bindings/wasm/.license_template
- bindings/wasm/docs/api-reference.md
- bindings/wasm/rustfmt.toml
- bindings/wasm/src/wasm_document.rs
- bindings/wasm/tests/wasm.rs
Adds `network` to the `WasmDocument` constructor / `previousMessageId` accessor
> Add missing wasm accessors

- bindings/wasm/src/wasm_document.rs
- examples/manipulate_did_document.rs
- identity-did/src/document/core_document.rs
- identity-iota/src/did/doc/iota_document.rs
- identity-iota/src/did/doc/iota_verification_method.rs
Remove the `impl Deref for IotaDocument` and re-implement `CoreDocument` methods on `IotaDocument` returning the correct (ie. IOTA-specific) types.
Specifically, the following functions have been linked to the `IotaDocument` type:
- `IotaDocument::controller()` - "unsafe", see Safety section below
- `IotaDocument::also_known_as()` - "safe"
- `IotaDocument::proof()` - "safe"
- `IotaDocument::methods()` - "unsafe", see Safety section below
- `IotaDocument::resolve()` - "unsafe", see Safety section below
- `IotaDocument::try_resolve()` - "unsafe, see Safety section below
- `IotaDocument::verifier()` - "safe"
- `IotaDocument::signer()` - "safe"
- `IotaDocument::services()` - "safe"
The `IotaDocument::try_from_core()` method has been updated to include validity checks for:
- …
> Return IOTA specific types for methods on IotaDocument

- identity-core/src/common/bitset.rs
- identity-core/src/common/one_or_many.rs
- identity-iota/src/did/doc/iota_document.rs
- identity-iota/src/did/url/iota_did.rs
Test the non-happy paths of `IotaDocument::try_from_core()`, `IotaDID::parse()`, and bitset serialize round trips.
`cargo test`
> Expand unit test coverage in bitset.rs, iota_did.rs, and iota_document.rs

- identity-iota/Cargo.toml
- identity-iota/src/did/doc/iota_document.rs
- identity-iota/src/did/url/iota_did.rs
Remove `Deref` impl from `IotaDID` to `DID`, re-implement methods on `IotaDID`.
N/A
Internal cleanup.
`cargo test`
> Remove IotaDID->DID Deref anti-pattern.

- bindings/wasm/examples/README.md
- bindings/wasm/examples/config.js
- bindings/wasm/examples/create_did.js
- bindings/wasm/examples/create_vc.js
- bindings/wasm/examples/create_vp.js
- bindings/wasm/examples/explorer_util.js
- bindings/wasm/examples/manipulate_did.js
- bindings/wasm/examples/merkle_key.js
- bindings/wasm/examples/node.js
- bindings/wasm/examples/resolution.js
- bindings/wasm/examples/revocation.js
Be more explicit throughout the WASM examples about the importance of using a consistent client configuration across calls (especially when using the testnet). This also updates the examples README to explicitly call out that calls must use a consistent client config.
#264 has information about how a mismatched network results in a cryptic failure.
idk how to test this locally :/ help!
> Rework WASM examples to explicitly use client configs.

- bindings/wasm/README.md
- bindings/wasm/docs/api-reference.md
- bindings/wasm/src/wasm_document.rs
- identity-iota/src/did/doc/iota_document.rs
- identity-iota/src/did/doc/iota_verification_method.rs
Add `IotaDocument::from_keypair_with_network(key, network)` and expose in WASM bindings (via optional `network` param in `fromKeyPair`).
This was a missing API which required a workaround (see https://github.com/iotaledger/identity.rs/issues/264#issuecomment-843364038).
This PR also include an example in the WASM examples README alongside the `identity.Document.fromKeyPair()` call (in comments).
#264 root cause was from a mismatch in network between document and node, and it wasn't obvious how to create a document from a keypair on the test network.
`cargo test`
> Add IotaDocument::from_keypair_with_network() and WASM binding.

- bindings/wasm/docs/api-reference.md
- bindings/wasm/package.json
- bindings/wasm/src/message/timing.rs
- bindings/wasm/src/wasm_document.rs
- identity-comm/src/message/timing.rs
Prevents adding the `BigUint64Array` type to WASM bindings
CI
> Use u32 for message delays

- docs/specs/iota_did_method_spec.md
To get started with my contributions, I fixed some typos I found while reading the did method spec.
> docs: Fix some typos in the method spec

- bindings/wasm/docs/api-reference.md
- bindings/wasm/src/crypto/digest.rs
- bindings/wasm/src/crypto/key_collection.rs
- bindings/wasm/src/wasm_verification_method.rs
Add blake2b to wasm bindings
CI
> Add blake2b to wasm bindings

- identity-core/src/crypto/key/key.rs
Based on a conversation with and code from @l1h3r, this reimplements `PublicKey` and `SecretKey` using generics rather than a macro.
> Reimpl `Key` with generics

- examples/account/config.rs
- identity-account/src/account/account.rs
- identity-account/src/account/builder.rs
- identity-iota/src/tangle/client_map.rs
Adds the ability to configure `Client` instances used by `Account` internals
Examples and tests
> Add ability to configure account clients

- .github/workflows/coverage.yml
- .github/workflows/format.yml
- .github/workflows/scripts/coverage.sh
Fix attempt for inconsistent Github Actions failures when downloading crates.
Pin the nightly Rust toolchain version in the `coverage` and `format` actions to `nightly-2021-07-05`.
The fix was suggested at the following link: https://github.community/t/failed-sending-data-to-the-peer-connection-died-tried-5-times-before-giving-up/189130
Github Actions pipeline tested against this PR.
> Fix pipeline download failures

- Cargo.toml
- identity-account/Cargo.toml
- identity-account/src/account/builder.rs
- identity-account/src/error.rs
- identity-account/src/lib.rs
- identity-account/src/storage/mod.rs
It should be possible to compile the upcoming identity actor to WebAssembly. It will use types from the account crate, and the account crate is not Wasm compatible due to a dependency on stronghold. This PR adds features to the account crate to opt-in to stronghold support - which is enabled by default - but can be opted out of to enable compilation to Wasm.
There is a weird issue with `tokio`, where even if we specify it to only use feature `sync` for example, it will still depend on the `mio` crate, even though it shouldn't. This may be happening due to how cargo selects features, and I've described the issue in some detail in the `toml` file. Fortunately, this can be worked around by specifying dependencies via git rather than crates.io. Makes it a bit less ergonomic to work with, i.e. …
> Add features to account to allow wasm compilation

- identity-core/Cargo.toml
Fix cyclic dependency when an updated version of [iota.rs](https://github.com/iotaledger/iota.rs) is in the dependency tree.
Remove unused `"preserve_order"` feature flag for `serde_json` which was causing a cyclic dependency, see issue #315 for context. Turns out we no longer need this feature to ensure the ordering of JSON-serialised data, as it was replaced by [`serde_jcs`](https://github.com/l1h3r/serde_jcs). Credit to @l1h3r for this.
NOTE: this PR does not update the version of [iota.rs](https://github.com/iotaledger/iota.rs) we use as there are errors compiling the wasm bindings with it, unrelated to the cyclic dependency which this fixes - PR #291 may address those issues.
Fixes issue #315
Describe the tests that you ran …
> Fix cyclic dependency

- .gitignore
- identity-account/src/stronghold/tests.rs
The `test_password_persistence` and `test_password_expiration` tests were inconsistently failing in the CI pipeline, and consistently failing when run inside a slow VM.
This PR raises the stronghold test password timeouts which were reduced in 4e4bd0ecc535c370677719b538a1cf13df3916b7 and improves handling on slow systems. The tests will still legitimately fail if e.g. the password clearing task never runs or runs too early.
All tests pass locally on Windows and Linux, and should pass the CI pipeline consistently.
> Fix inconsistent stronghold storage test

- .github/workflows/build-and-test.yml
Adds [`sccache`](https://github.com/mozilla/sccache) to the GitHub Actions `build-and-test` pipeline. Should hopefully speed up the CI jobs on all platforms by caching compilation of some crates. This only affects the `build-and-test` pipeline since it takes the longest but `sccache` should ideally be used for all jobs where it makes sense in the future.
This also fixes the cache restore keys: they weren't being used at all since it previously included the hash of Rust files in the key, which changes on every commit that touches the code.
Even with additional caching, the Windows job still takes significantly longer than the Linux/MacOS ones. This is exacerbated by the fact that the `test` step performs the last stage of compilation again after the `build` step. This needs to be …
> Add sccache to pipeline

- bindings/wasm/build/web.js
Updates the workaround for `webpack` not supporting `import.meta` properties, which causes an error when trying to use the identity Wasm web bindings with some frameworks, e.g. React.
We had a workaround for this exact issue, it just looks like the code generated by `wasm-bindgen` was changed recently so the workaround stopped working.
The fix is to use a build script to comment out the problematic line, which is never reached since we always pass in a valid path:
```
async function initWasm(input) {
if (typeof input === 'undefined') {
// input = new URL('identity_wasm_bg.wasm', import.meta.url);  <--- HERE
}
```
**This will require a new release of the `npm` package for `@iota/identity/wasm@dev`.**
Fixes issue #338 
Generated the web package locally with `npm run build:web` and checked …
> Fix import.meta error

- .github/workflows/audit.yml
- .github/workflows/build-and-test.yml
- .github/workflows/examples.yml
- bindings/wasm/.gitignore
- bindings/wasm/README.md
- bindings/wasm/cypress.json
- bindings/wasm/cypress/integration/browser_test.js
- bindings/wasm/examples/browser/create_did.js
- bindings/wasm/examples/browser/create_vc.js
- bindings/wasm/examples/browser/create_vp.js
- bindings/wasm/examples/browser/main.js
- bindings/wasm/examples/browser/mainpulate_did.js
- bindings/wasm/examples/browser/merkle_key.js
- bindings/wasm/examples/browser/resolve.js
- bindings/wasm/examples/browser/revocation.js
- bindings/wasm/examples/browser/utils.js
- bindings/wasm/examples/node/config.js
- bindings/wasm/examples/node/create_did.js
- bindings/wasm/examples/node/create_vc.js
- bindings/wasm/examples/node/create_vp.js
- bindings/wasm/examples/node/explorer_util.js
- bindings/wasm/examples/node/manipulate_did.js
- bindings/wasm/examples/node/merkle_key.js
- bindings/wasm/examples/node/node.js
- bindings/wasm/examples/node/resolution.js
- bindings/wasm/examples/node/revocation.js
- bindings/wasm/examples/node/test.js
- bindings/wasm/package.json
- bindings/wasm/yarn.lock
This PR adds the Wasm Node.js and browser examples to a new GitHub Actions job. The new job runs periodically, similar to the `audit` task, rather than on pull requests to avoid slowing down the existing CI pipeline.
This also fixes several of the Wasm examples that were broken recently, including the ones in the README.md file. Note that the examples in README.md are also tested in the CI with [`txm`](https://github.com/anko/txm) (node examples only).
Node examples are tested using [`jest`](https://jestjs.io/), while browser examples are tested using [`cypress`](https://www.cypress.io/). This is due to there being compatibility problems with running the browser Javascript code in [`jest`](https://jestjs.io/), as it relies on browser APIs for e.g. generating secure random numbers, and …
> Add Wasm examples to CI

- documentation/docusaurus.config.js
- documentation/package.json
- documentation/yarn.lock
Added Remark plugin to remove HTML comments before processing the include plugin. Now the include plugin no longer crashes.
> Fix docusaurus build

- bindings/wasm/build/lints.js
- bindings/wasm/build/node.js
- bindings/wasm/build/web.js
- bindings/wasm/docs/api-reference.md
- bindings/wasm/src/common/timestamp.rs
These methods use `i64` in their method signatures, which causes a dependency on `BigInt64Array` on the JavaScript side. Since we already have `to_rfc3339` and `parse` methods, there are alternatives available. Thus, removing these methods is a good enough fix.
Also added a lint to the build scripts that checks the output for these imports and aborts the build process in that case.
fixes #362
Added lint scripts that run post-build.
> Remove `toUnix` and `fromUnix` methods in `WasmTimestamp`

- bindings/wasm/docs/api-reference.md
- bindings/wasm/package-lock.json
- bindings/wasm/package.json
Small version release for the `BigInt64Array` fix (#365) for Wasm.
> Bump version to 0.3.7 for @iota/identity-wasm@dev

- identity-account/Cargo.toml
- identity-account/src/error.rs
- identity-account/src/storage/stronghold.rs
- identity-account/src/stronghold/context.rs
- identity-account/src/stronghold/snapshot.rs
- identity-account/src/stronghold/tests.rs
- identity-core/Cargo.toml
- identity-core/src/crypto/signature/ed25519.rs
- identity-core/src/utils/ed25519.rs
- identity-iota/Cargo.toml
This migrates the riker-based stronghold to the new actix-based version. The system was previously set up in a static context, and I've kept that pattern. The `actix::System` required to run stronghold is essentially a single-threaded tokio runtime (the so-called `LocalSet`). Since we are already running in a `tokio` runtime (per the examples), we cannot start an `actix::System` in the same thread. Doing so results in a: `Cannot start a runtime from within a runtime. This happens because a function (like block_on) attempted to block the current thread while the thread is being used to drive asynchronous tasks.`
Moreover, some thread needs to actively drive the `actix::System`'s event loop, i.e. `system.run()`, so this blocking operation essentially requires the extra thread.
It would be …
> Migrate to latest actix-based Stronghold

- bindings/wasm/docs/api-reference.md
- bindings/wasm/examples/browser/create_did.js
- bindings/wasm/examples/node/create_did.js
- bindings/wasm/package-lock.json
- bindings/wasm/package.json
- bindings/wasm/src/did/wasm_document.rs
Add `set_message_id` to `WasmDocument` to allow setting the `messageId` on DID documents in the wasm bindings. 
Bump version to 0.3.8.
Tests, examples pass locally.
> Bump to 0.3.8 for @iota/identity-wasm@dev, add set_message_id

- .github/workflows/build-and-test.yml
Makes `sccache` installation a bit faster on macOS by adding the `--preinstall` flag to the `brew update` command, which skips some checks that are redundant when running `brew update` just before `brew install`
N/A
CI ran successfully
> Make sccache installation a bit faster on macOS

- bindings/wasm/package-lock.json
- bindings/wasm/package.json
- bindings/wasm/src/did/wasm_document_diff.rs
Fix `message_id` returning the `previous_message_id` on `WasmDiffDocument` in the wasm bindings.
Bump version to 0.3.9.
Tests and examples pass locally.
> Bump to 0.3.9 for @iota/identity-wasm@dev, fix messageId 

- bindings/wasm/docs/api-reference.md
- bindings/wasm/examples/browser/private_tangle.js
- bindings/wasm/examples/node/private_tangle.js
- bindings/wasm/src/did/wasm_document.rs
- bindings/wasm/src/tangle/network.rs
- examples/account/private_tangle.rs
- examples/low-level-api/private_tangle.rs
- identity-account/src/account/builder.rs
- identity-account/tests/commands.rs
- identity-iota/src/did/doc/iota_verification_method.rs
- identity-iota/src/did/macros.rs
- identity-iota/src/did/url/iota_did.rs
- identity-iota/src/tangle/client_builder.rs
- identity-iota/src/tangle/client_map.rs
- identity-iota/src/tangle/mod.rs
- identity-iota/src/tangle/network.rs
- identity/src/lib.rs
Add a newtype wrapper `NetworkName` to replace occurrences of unchecked string representations of IOTA DID network names.
This helps ensure network names comply with the [IOTA DID method spec](https://github.com/iotaledger/identity.rs/blob/dev/documentation/docs/specs/iota_did_method_spec.md):
- at most 6 characters
- only alphanumeric characters in `{0-9, a-b}`
There are several breaking changes:
- remove unused `did!` macro (which just unwrapped errors from `try_did!` as panics)
- rename `IotaDID::with_network` to `IotaDID::new_with_network`
- rename `Network::from_name` to `Network::try_from_name`
- rename `try_did!` to `try_construct_did!`
- change `IotaDID` validation to error on invalid network strings
- change `Network::explorer_url` return type from `Result` to `Option`
- change …
> Refactor `NetworkName`

- identity-iota/src/tangle/network.rs
Extend Network doc comment for other networks, because without it it's not clear why it might not work
> Extend Network doc comment for other networks

- .github/workflows/build-and-test.yml
Change the Rust build step in the build-and-test GitHub Actions workflow to avoid recompilation and improve CI speed.
The command changes from:
`cargo build --all --release`
to: 
`cargo test --all --release --no-run`
This is done because the compilation performed in the "Run Tests" step typically takes a significant amount of time (roughly 13 minutes) while the tests themselves complete in a few seconds to one minute. The change avoids some recompilation by compiling the tests and examples at the same time as the rest of the library, rather than separately. 
The disadvantages are that the build step is slightly different than it would be for a regular release as a library, and the tests/examples may fail compilation while a regular build may have passed. This would make debugging why a CI …
> Change build workflow step to avoid recompilation

- examples/Cargo.toml
- examples/account/basic.rs
- examples/account/lazy.rs
- examples/account/methods.rs
- examples/account/private_tangle.rs
- examples/account/services.rs
- examples/account/signing.rs
- examples/account/stronghold.rs
- identity-account/src/account/account.rs
- identity-account/src/account/builder.rs
- identity-account/src/identity/identity_index.rs
- identity-account/src/storage/memstore.rs
- identity-account/src/storage/stronghold.rs
- identity-account/src/storage/traits.rs
- identity-account/tests/lazy.rs
Give users of the `Account` more control over when to publish to the tangle. For example, if an identity is created and a service and a method are added subsequently, this would currently result in three messages being published to the tangle. With this PR, all changes can be applied to a locally stored document, and then published in a single message. That increases the overall speed, since there are fewer network interactions and less Proof-of-Work, and reduces the used storage space on nodes.
The `Account` already organizes the updates to a document in `Commit`s. Each `Commit` is identified by a `Generation` (an incrementing `u32`). The basic idea is to store which generation was last published to the tangle, and when updating, publishing all commits that have been added since.
One …
> Enable lazy tangle updates in the `Account`

- README.md
Previously, the example used `document1` to refer to the DID, whereas the "document" isn't resolved until `account.resolve_identity()` is called. This change fixes a mismatch between variable name and what it actually represents.
**NOTE:** The repl.it example at https://wiki.iota.org/identity.rs/getting-started/decentralized_identifiers/create should also be updated as well, but I'm not sure where that lives.
Also, consistent periods at end of comments 🙃 
N/A
N/A - Documentation change in README.md.
> Rename document1 to did1 in README example.

- bindings/wasm/Cargo.toml
Explicitly enable the tokio "rt" feature in the wasm bindings to fix compilation of the bee-runtime dependency.
Fixes issue #403 
Compilation of the wasm bindings succeeds and all tests and examples pass locally.
> Fix wasm compilation

- bindings/wasm/README.md
- bindings/wasm/docs/api-reference.md
- bindings/wasm/src/tangle/network.rs
- bindings/wasm/tests/wasm.rs
- documentation/docs/specs/iota_did_method_spec.md
- identity-account/src/tests/commands.rs
- identity-account/src/tests/lazy.rs
- identity-iota/src/did/doc/iota_document.rs
- identity-iota/src/did/url/iota_did.rs
- identity-iota/src/tangle/network.rs
Replaces all references to the `testnet` with `devnet`. This includes the network name, default node URL, explorer URL, method specification, examples, and documentation.
This is due to the discontinuation of the Chrysalis P2 `testnet` in favour of the Chrysalis P2 `devnet`.
- `Network::Testnet` -> `Network::Devnet`
- "test" is no longer a reserved network name
- "dev" is now a reserved network name
- `iota:did:test` -> `iota:did:dev`
Fixes issue #358 
Created a valid DID using the `Network::Devnet`, viewable at: https://explorer.iota.org/devnet/identity-resolver/did:iota:dev:GimqiaYtv1aNnxQS3c6sfTst6gakiZg3UwWhxoazQv59
All tests and examples pass locally.
> Replace `testnet` with `devnet`

- bindings/wasm/docs/api-reference.md
- bindings/wasm/package-lock.json
- bindings/wasm/package.json
- bindings/wasm/src/did/wasm_document_diff.rs
Bump the `@iota/identity-wasm@dev` version to 0.3.11 for the change to `devnet`: #405.
Add `proof` field getter for WasmDocumentDiff.
Wasm examples pass locally
> Bump to 0.3.11 for @iota/identity-wasm@dev, add proof getter

- documentation/docs/getting-started/decentralized_identifiers/resolve.md
Add some content to the DID Resolution wiki page. This is by no means complete, but thought it would be better to have some minimal content instead of simply TODO. Happy to make any other key additions you feel are necessary before publishing.
Ideally we'd have either a tabbed UI or Replit with complete code examples demonstrating this. I also noticed on the previous page on creation the WASM examples don't use the Account API, so wasn't sure if I should include the non-account API now or add the WASM at the same time the other example is changed.
N/A
Built locally
> Add stub content to IOTA DID Resolution wiki page.

- identity-account/src/account/account.rs
- identity-account/src/events/command.rs
- identity-account/src/events/event.rs
- identity-account/src/identity/identity_state.rs
- identity-account/src/storage/stronghold.rs
- identity-account/src/tests/commands.rs
- identity-account/src/types/key_location.rs
- identity-core/src/common/fragment.rs
- identity-iota/src/did/doc/iota_document.rs
- identity/benches/benchmark.rs
- Rename the last remaining occurrences of auth chain to int chain. This is a breaking change because multiple method names have changed.
- Add the default verification method we use to sign document update messages as a generic verification method, instead of only as an [authentication](https://www.w3.org/TR/did-core/#authentication) method. However, the `authentication` verification relationship is attached to the method. An example of a newly generated did document thus looks like:
```
{
"id": "did:iota:dev:7uUb2ES6qnuzsKjWG7Ft8iVz5Q7S3ZgXrcJGTiKskBi8",
"verificationMethod": [
{
"id": "did:iota:dev:7uUb2ES6qnuzsKjWG7Ft8iVz5Q7S3ZgXrcJGTiKskBi8#_sign-0",
"controller": "did:iota:dev:7uUb2ES6qnuzsKjWG7Ft8iVz5Q7S3ZgXrcJGTiKskBi8",
"type": "Ed25519VerificationKey2018",
"publicKeyBase58": …
```
> Add default signing key as a generic verification method

- bindings/wasm/README.md
- bindings/wasm/docs/api-reference.md
- bindings/wasm/examples/src/create_did.js
- bindings/wasm/examples/src/create_vp.js
- bindings/wasm/examples/src/private_tangle.js
- bindings/wasm/src/did/wasm_did.rs
- bindings/wasm/src/did/wasm_document.rs
- bindings/wasm/tests/wasm.rs
- examples/account/private_tangle.rs
- examples/low-level-api/create_did.rs
- examples/low-level-api/private_tangle.rs
- identity-account/src/events/command.rs
- identity-account/src/identity/identity_create.rs
- identity-account/src/tests/commands.rs
- identity-account/src/tests/lazy.rs
- identity-iota/src/chain/diff_chain.rs
- identity-iota/src/did/doc/iota_document.rs
- identity-iota/src/did/doc/iota_verification_method.rs
- identity-iota/src/did/url/iota_did.rs
- identity-iota/src/error.rs
- identity-iota/src/tangle/network.rs
- identity/benches/benchmark.rs
- identity/benches/diff_chain.rs
This replaces the constructor for `WasmDocument` to fix a type mismatch in the generated bindings. Several `Document` constructors are also replaced with a single `new()` function in both Rust and Wasm. This is for consistency and to clarify the canonical method of constructing a new `Document`.
~~The downside is that this removes the ability for a developer to pass in the desired fragment name for the authentication verification method on a newly generated `Document` in Wasm (e.g. instead of "#authentication" one could specify "#customkey123"). This was not possible in Rust, if that behaviour is still desired we should add it in this PR to both languages.~~ 
Edit: added the ability to set the default verification method fragment in both Rust and Wasm.
**Breaking changes**:
- replace …
> Fix Document constructor Typescript bindings

- identity-iota/src/credential/validator.rs
Small patch which removes an invalid signature check on issuer and subject documents from `CredentialValidator` which was causing otherwise valid credentials to fail verification.
Since the `CredentialValidator` is due for a refactor in #312 only this particular bug was addressed.
Fixes issue #489 
The bug reproduction example in #489 succeeds with this PR and all local tests pass. Unfortunately this is difficult to test since it involves resolving documents from the Tangle.
> Fix credential validation failing for documents with diff updates

- bindings/wasm/Cargo.toml
- identity-iota/Cargo.toml
Updates the `iota-client` dependency to use the published 1.1.0 crate instead of referencing a git commit, which was causing a build error in our dependency chain (#502).
Also removes workarounds for `reqwest` and `tokio` features in the wasm bindings which are no longer necessary.
fixes issue #502 
Local tests and examples pass locally, including Wasm examples.
> Update iota-client dependency

- bindings/wasm/src/did/wasm_document.rs
- examples/account/manipulate_did.rs
- examples/low-level-api/common.rs
- examples/low-level-api/manipulate_did.rs
- examples/low-level-api/merkle_key.rs
- examples/low-level-api/resolve_history.rs
- examples/low-level-api/revoke_vc.rs
- identity-account/src/account/account.rs
- identity-account/src/error.rs
- identity-account/src/tests/updates.rs
- identity-account/src/updates/error.rs
- identity-account/src/updates/update.rs
- identity-did/src/document/core_document.rs
- identity-did/src/error.rs
- identity-did/src/verifiable/document.rs
- identity-iota/src/did/doc/iota_document.rs
- identity-iota/src/tangle/publish.rs
To prevent users from creating invalid documents, some checks were moved from the account to the lower-level crates.
- Move existence and duplication checks to `CoreDocument`.
- Move embedded check to `CoreDocument` methods that modify relationships. This check ensures that relationships cannot be attached or detached from embedded methods.
- Remove unused error types that were duplicated across crates (e.g. `MethodNotFound`) and use the variant from the `identity-did` crate.
- Improve documentation of modified methods.
- Rename `AttachMethod` to `AttachMethodRelationship`
- Rename `DetachMethod` to `DetachMethodRelationship`
fixes #495 
Insertion and removal as well as attach and detach tests were modified appropriately to test …
> Check for existence & duplication of methods in `CoreDocument`

- examples/account/config.rs
- examples/account/create_did.rs
- examples/account/lazy.rs
- examples/account/manipulate_did.rs
- examples/account/multiple_identities.rs
- examples/account/signing.rs
- identity-account/src/account/account.rs
- identity-account/src/account/builder.rs
- identity-account/src/account/config.rs
- identity-account/src/storage/stronghold.rs
- identity-account/src/tests/account.rs
Moves the drop trait to `Stronhold`.
closes #452 
Multiple accounts with the same `AccountSetup` were created, and performed multiple actions concurrently, before being dropped. 
> Move drop trait to stronghold

- identity-core/src/crypto/key/pair.rs
- identity-core/src/crypto/proof/jcs_ed25519.rs
- identity-core/src/crypto/signature/ed25519.rs
- identity-core/src/utils/ed25519.rs
The ed25519 private keys generated and parsed by this library all satisfy the definition given in [RFC 8032](https://datatracker.ietf.org/doc/html/rfc8032#section-3.2). However it is quite common for other implementations to use another format as explained in [this blog post](https://blog.mozilla.org/warner/2011/11/29/ed25519-keys/). 
Due to the various conventions in use it is important for us to document which private key format our library assumes which is what this PR aims to do.  This is done by both including more documentation, but also by modifying some parsing checks to be more precise. 
The relevant tests have been modified to reflect the new changes. All …
> Enforce Ed25519 private key length

- .github/workflows/examples.yml
Pins `txm` to install version 7 (currently 7.4.7) in the GitHub Actions examples workflow.
This is due to a recent breaking change to `txm` in version 8.0.0 (https://github.com/anko/txm/releases/tag/v8.0.0) which causes the examples workflow to fail with the following error:
```
Run npm run test:readme
> @iota/identity-wasm@0.4.0 test:readme
> txm README.md
file:///opt/hostedtoolcache/node/16.13.0/x64/lib/node_modules/txm/src/cli.js:16
const programName = Object.entries(packageMetadata.bin)
^
TypeError: Cannot convert undefined or null to object
at Function.entries (<anonymous>)
at file:///opt/hostedtoolcache/node/16.13.0/x64/lib/node_modules/txm/src/cli.js:16:28
at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
at async Promise.all (index 0)
at async ESMLoader.import …
```
> Fix `txm` version in GitHub Actions

- identity-iota/src/chain/integration_chain.rs
- identity-iota/src/error.rs
- identity-iota/src/tangle/client.rs
Throw a more informative `DIDNotFound` error message when the network of the DID does not match that of the `Client` when resolving it. 
Removes several defunct and unused error variants from `identity-iota`.
Fixes #505 
Tests and examples pass locally.
> Improve client error messages

- bindings/wasm/docs/api-reference.md
- identity-diff/Cargo.toml
- identity-diff/README.md
- identity-diff/derive/Cargo.toml
- identity-diff/src/lib.rs
- identity-diff/tests/derive_enum_test.rs
- identity-diff/tests/derive_struct_test.rs
- Renames `identity-derive` to `identity-diff-derive` for clarity and to reserve `identity-derive` for future use.
- Feature-gates `identity-diff-derive` in `identity-diff` behind a new `derive` feature.
- Updates `identity-diff-derive` to Rust edition 2021 in line with the rest of the projects.
The `Diff` proc-macro from `identity-diff-derive` is only used within `identity-diff` tests currently, so feature-gating it is a minor optimisation for releases. With these changes, `identity-diff-derive` no longer appears in the Wasm bindings dependency tree.
Local tests and Wasm examples pass.
> Add `identity-diff` derive feature gate

- libjose/Cargo.toml
- libjose/src/utils/crypto/key_repr.rs
Upgrades the `rsa` crate dependency to version `0.5` in our `libjose` crate. This removes our dependency on `simple_asn1 v0.5.4` which is necessary in order to eventually migrate away from the `chrono` crate (Issue #442).  
I successfully managed to run the following test suites in libjose locally:
`cargo test --features test-rsa-enc`, 
`cargo test --features test-rsa-sig`, 
`cargo test --all-features --release` 
> update to rsa 0.5 in libjose

- identity-account/src/account/account.rs
- identity-did/src/resolution/resource.rs
Added `#[allow(clippy::large_enum_variant)]` for the `PrimaryResource` enum until the resolver gets refactored. Also renamed a private field in `Account` to make `cargo check` pass without warnings. 
> Fix lint warnings

- bindings/wasm/Cargo.toml
- bindings/wasm/docs/api-reference.md
- identity-account/Cargo.toml
- identity-comm/Cargo.toml
- identity-core/Cargo.toml
- identity-credential/Cargo.toml
- identity-did/Cargo.toml
- identity-did/src/resolution/resource.rs
- identity-diff/Cargo.toml
- identity-diff/derive/Cargo.toml
- identity-iota/Cargo.toml
- identity-iota/src/did/doc/iota_document.rs
- identity/Cargo.toml
Hot fix for a compilation error on the **main** branch reported in #524 due to the `iota-client` git dependency being updated.
Bumps the `iota-client` version to 1.1 from crates.io.
This is the same fix performed for the dev branch in #503. There should be no functional changes from applying this patch.
Edit: bumps identity to 0.4.1
Fixes issue #524
Tests and examples pass locally.
> Bump `iota-client` version to 1.1

- identity-iota/Cargo.toml
Updates the `iota-client` dependency to a later git revision to fix a bug causing compilation to fail due to breaking changes in `bee-rest-api` 0.1.6.
~~Pins the `bee-rest-api` dependency to version 0.1.3. This is to fix breaking changes introduced in `bee-rest-api` 0.1.6 which cause compilation of `iota-client` to fail.~~
~~Should be temporary until https://github.com/iotaledger/iota.rs/pull/766 is merged.~~
Compilation error:
```
Compiling iota-client v1.1.0 (https://github.com/iotaledger/iota.rs?rev=c48db779d2162b9a3037ee63c4d1e267d04633eb#c48db779)
error[E0609]: no field `0` on type `ReceiptsResponse`
Error:     --> /Users/runner/.cargo/git/checkouts/iota.rs-1792f679be51837c/c48db77/iota-client/src/client.rs:1063:31
|
1063 |         Ok(resp.data.receipts.0)
| …
```
> Update `iota-client` dependency

- identity-iota/Cargo.toml
Updates the version of `iota-client` to fix compilation by using the latest `bee-rest-api` 0.1.7 version. See https://github.com/iotaledger/bee/issues/869 .
~~Draft PR until https://github.com/iotaledger/iota.rs/pull/767  is merged.~~
Tests and Wasm examples pass locally.
> Update `iota-client` version

- bindings/wasm/tests/wasm.rs
- identity-core/Cargo.toml
- identity-core/src/common/timestamp.rs
- identity/Cargo.toml
After migrating to `time` we got the following error `panicked at 'time not implemented on this platform', library/std/src/sys/wasm/../unsupported/time.rs:39:9` when running the node examples. This PR fixes that. 
Runs successfully under 
`npm run build && npm run build:examples && npm run test:node && npm run test:browser` called from the `bindings/wasm` directory. Also passes `cargo test` called from the root directory. 
> Fix `Timestamp` in the Wasm bindings

- bindings/wasm/Cargo.toml
Removes a dev dependency on `chrono` in the Wasm/JS bindings.
It was previously used to enable a feature needed for the Wasm bindings but our dependencies no longer use `chrono`.
Fixes issue #440 
Passes 
`npm run build && npm run build:examples && npm run test:node && npm run test:browser` 
and `cargo test` locally. 
> Remove `chrono` dev-dependency in Wasm bindings

- .cargo/audit.toml
- .github/workflows/audit.yml
Ignore [RUSTSEC-2021-0127](https://rustsec.org/advisories/RUSTSEC-2021-0127.html) advising that the `serde_cbor` crate is unmaintained to prevent audit checks failing when releasing to main (all other advisories have been resolved at this point).
Issue #518 will remain open to track this. We also do not directly use `serde_cbor`, it is only a dependency of `criterion.rs` which we use for benchmarking. Just because it is unmaintained does not mean there is a vulnerability right now so it seems fine to ignore repeat warnings and wait for `critertion.rs` to migrate away from `serde_cbor`.
Related to issue #518 
`cargo audit` ran locally and ignored the advisory.
> Ignore `serde_cbor` unmaintained advisory in audit

- bindings/wasm/docs/api-reference.md
- bindings/wasm/examples/src/create_vc.js
- bindings/wasm/examples/src/create_vp.js
- bindings/wasm/examples/src/merkle_key.js
- bindings/wasm/src/credential/credential.rs
- bindings/wasm/src/credential/mod.rs
- bindings/wasm/src/credential/presentation.rs
- bindings/wasm/src/did/wasm_document.rs
This renames `VerifiableCredential` to `Credential` and `VerifiablePresentation` to `Presentation` in the Wasm bindings for parity with the core Rust library.
Wasm tests and examples pass locally.
> Rename Wasm `VerifiableCredential`, `VerifiablePresentation` 

- bindings/wasm/build/node.js
fix issue with multiple node-fetch versions conflicting in the global namespace
fixes issue #482
Tested integration in IOTA Explorer.
> fix node-fetch conflict when multiple versions are included

- .github/workflows/coverage.yml
- .github/workflows/format.yml
- .github/workflows/scripts/coverage.sh
- identity-account/src/account/builder.rs
- identity-account/src/account/publish_options.rs
- identity-account/src/updates/macros.rs
- identity-account/src/updates/update.rs
- identity-core/src/crypto/key/collection.rs
- identity-core/src/crypto/signature/signature_options.rs
- identity-did/src/did/did_url.rs
- identity-did/src/verifiable/document_signer.rs
- identity-did/src/verifiable/document_verifier.rs
- identity-did/src/verifiable/verifier_options.rs
- identity-iota/src/document/iota_document.rs
- identity-iota/src/tangle/client_builder.rs
Annotates builder functions with `#[must_use]` (where the result type does not already have that lint, e.g. `Result` is already `must_use`) and other minor non-functional changes to appease `clippy`.
Updates the pinned Rust nightly version in GitHub Actions from `nightly-2021-12-05` to `nightly-2022-01-08`.
Tests and examples pass locally.
> Fix clippy lints

- identity-iota/Cargo.toml
- identity-iota/src/tangle/client_builder.rs
This enables the `pow-fallback` feature for `iota-client`, which means publishing messages falls back to performing proof-of-work locally (on the client) when no nodes support remote proof-of-work.
NOTE: this changes the behaviour of the `local_pow` setting on the `ClientBuilder`, making it a preference whether or not to try remote PoW first before using local PoW rather than a hard setting. Since the `pow-fallback` is a compile-time feature we cannot change whether or not to fallback at runtime. This change may be temporary.
Tested with a local one-click-Tangle with remote PoW enabled and disabled on the Hornet node.
1) When **remote PoW on the node is disabled** and **local PoW on the client is false** **_without local fallback from this PR_**, we get the following error from the …
> Enable local proof-of-work fallback

- bindings/wasm/docs/api-reference.md
- bindings/wasm/src/did/wasm_document.rs
- bindings/wasm/src/did/wasm_resolved_document.rs
Fixes the names of two functions in the Wasm bindings:
- `ResolvedDocument.integrationMessageId` was incorrectly exported as `metadataPreviousMessageId`.
- `Document.mergeDiff` was exported as `merge_diff`.
Technically a breaking change but really just fixes it to be as intended.
Unit tests and examples pass locally.
> Fix `ResolvedDocument.integrationMessageId`

- bindings/wasm/src/lib.rs
- examples/account/create_did.rs
- identity-account/src/account/account.rs
Changes the visibility of `Account::state` to `pub(crate)`, because the `IdentityState` is not required to be exposed to users. Moreover, `IdentityState` is planned to be removed with #508. This PR is supposed to prevent unnecessary work on the account bindings (e.g. #574).
n/a
> Change `Account::state` visibility to `pub(crate)`

- bindings/wasm/examples/src/diff_chain.js
- documentation/docs/specs/did/iota_did_method_spec.md
- examples/low-level-api/diff_chain.rs
- identity-did/src/diff/diff_document.rs
- identity-did/src/diff/diff_method.rs
- identity-did/src/diff/diff_service.rs
- identity-diff/src/object.rs
- identity-iota/src/diff/diff_iota_document_metadata.rs
- identity-iota/src/tangle/message/compression_brotli.rs
- identity-iota/src/tangle/message/message_ext.rs
Fixes a bug introduced in #598 where `DiffMessages` from the Tangle no longer match the expected signature due to serialization differences, causing verification in `DiffChain` to fail and any diffs that add a `Service` or `VerificationMethod` to be rejected.
Before #598, the `DiffIotaDocument` was serialised to a JSON string first for the `DiffMessage::diff` field. This meant the signature verification of `DiffMessage` was not affected, since `DiffIotaDocument` was not deserialised then serialised again during verification.
The root cause is due to how `properties` in `Service` and `VerificationMethod` are handled in their `ServiceDiff::into_diff` and `DiffMethod::into_diff` implementations: empty `properties` (of type `Object` i.e. `BTreeMap`) would be diffed to `Some(DiffHashMap([]))`. …
> Fix diff properties (de)serialization

- identity-iota/Cargo.toml
Bump `iota-client` from 1.1 to the pinned git-revision used on `dev`. This changes the `wasm-timer` dependency to use the forked version from @PhilippGackstatter (https://github.com/PhilippGackstatter/wasm-timer?rev=448c2be0c4feeb6b5df1da265489232dff2f03c1), which calls `js_sys::global` rather than `web_sys::window`.
This is to fix a bug currently encountered in 0.4.2 where the following block of generated code throws an undefined error when called under uncertain circumstances:
```js
module.exports.__wbg_instanceof_Window_c4b70662a0d2c5ec = function(arg0) {
var ret = getObject(arg0) instanceof Window;
return ret;
};
```
With this change, the function is no longer generated or called.
Wasm tests and examples pass locally for Node.js and the browser.
> Fix `Window` undefined error

- bindings/wasm/examples/src/diff_chain.js
- examples/low-level-api/diff_chain.rs
- identity-did/src/diff/diff_document.rs
- identity-did/src/diff/diff_method.rs
- identity-diff/derive/src/model.rs
- identity-diff/src/object.rs
- identity-iota/Cargo.toml
- identity-iota/src/chain/diff_chain.rs
- identity-iota/src/chain/document_chain.rs
- identity-iota/src/diff/diff_iota_document_metadata.rs
- identity-iota/src/document/iota_document.rs
- identity-iota/src/document/iota_document_metadata.rs
- identity-iota/src/tangle/message/compression_brotli.rs
- identity-iota/src/tangle/message/message_ext.rs
Fixes the `DiffChain` rejecting `DiffMessages` that update document sections added in previous diffs. From the example given in #593: adding a service in a diff update then editing or removing it in another diff update will result in the latter update being rejected/discarded by the `DiffChain` during resolution.
Thank you to @PhilippGackstatter and @abdulmth for identifying and investigating the issue!
This also flattens the properties of `DocumentMetadata` serialization (this ensures unhandled fields are captured during deserialization), which may lead to breaking changes if any existing user-defined custom fields conflict with hardcoded field names.
**WARNING:** this may result in resolutions of IOTA DID Documents that contain diff updates being different after this is merged.
Fixes …
> Fix dependent diff updates being rejected

- bindings/wasm/docs/api-reference.md
- bindings/wasm/examples/src/create_did.js
- bindings/wasm/examples/src/diff_chain.js
- bindings/wasm/examples/src/manipulate_did.js
- bindings/wasm/examples/src/merkle_key.js
- bindings/wasm/examples/src/private_tangle.js
- bindings/wasm/examples/src/resolve_history.js
- bindings/wasm/examples/src/revoke_vc.js
- bindings/wasm/package.json
- bindings/wasm/src/did/mod.rs
- bindings/wasm/src/did/wasm_did.rs
- bindings/wasm/src/did/wasm_did_url.rs
- bindings/wasm/src/did/wasm_document.rs
- bindings/wasm/src/did/wasm_verification_method.rs
- bindings/wasm/src/error.rs
- bindings/wasm/src/tangle/client.rs
- bindings/wasm/src/tangle/network.rs
- bindings/wasm/tests/wasm.rs
This adds the `UMethodQuery` and `UDID` (naming convention open to change) Typescript union types. This pattern allows us to create analogues for generic types in function parameters, such as `MethodQuery` which takes either an `IotaDIDUrl` or `String`. This is to enhance the developer-friendliness of our Wasm API by removing unnecessary `toString` invocations and allowing pseudo-generic, polymorphic function parameters.
~~`export type UMethodQuery = DIDUrl | string;`~~
~~`export type UDID = DID | string;`~~
Edit: this PR no longer exports the union types to Typescript, instead it injects the union into the function parameter definitions directly.
E.g.
```ts
signSelf(key_pair: KeyPair, method_query: DIDUrl | string): void;
```
With this change, all of the following work:
```ts …
```
> Add union type parameters

- identity-did/src/verification/method_query.rs
- identity-iota/src/document/iota_document.rs
This updates `MethodQuery` to match on the DID as well as the fragment when the query includes a full DID-Url.
This fixes the following edge-cases:
- adding a method to a document with an ID field of a different DID (typically a controller DID Document) but the same fragment as an existing method.
- resolving such a method by specifying its full ID (previously would return the first method that matched the fragment).
- verifying a document signed with such a method.
The specification seems to allow adding methods and services to a DID Document which reference a different DID. We added support for signatures from such methods in #458 but duplicate fragments was still an edge-case.
NOTE: this affects all functions that resolve methods (including verifying signatures since that resolves the …
> Support verification methods with the same fragment

- bindings/wasm/package-lock.json
- bindings/wasm/package.json
Updates the `http-server` dev-dependency to the latest version (14.1.0) to address a security warning:
https://github.com/iotaledger/identity.rs/security/dependabot/bindings/wasm/package-lock.json/ecstatic/open
Wasm tests and browser examples pass locally.
`npm run example:browser` worked interactively.
> Update http-server to 14.1.0

- identity-did/src/diff/diff_document.rs
- identity-did/src/document/core_document.rs
- identity-iota/src/document/iota_document.rs
Changes the `CoreDocument::also_known_as` field from `Vec<Url>` to `OrderedSet<Url>` to comply with the DID specification: https://www.w3.org/TR/did-core/#also-known-as 
> The alsoKnownAs property is OPTIONAL. If present, the value MUST be a [set](https://infra.spec.whatwg.org/#ordered-set) where each item in the set is a [URI](https://www.w3.org/TR/did-core/#dfn-uri) conforming to [[RFC3986]](https://www.w3.org/TR/did-core/#bib-rfc3986).
where "set" is defined to be an `OrderedSet`: https://infra.spec.whatwg.org/#ordered-set .
Besides the API changes, this may break DID Documents which have duplicate entries in their `alsoKnownAs` section.
This also adds `IotaDocument::also_known_as_mut()` since previously there was no safe way to update the field from `IotaDocument` without going …
> Change `also_known_as` type to `OrderedSet`

- bindings/wasm/package-lock.json
- bindings/wasm/package.json
Updates the `jsdoc-to-markdown` dev-dependency for the Wasm bindings to the latest version (7.1.1) to address security warnings:
- https://github.com/iotaledger/identity.rs/security/dependabot/bindings/wasm/package-lock.json/marked/open
- https://github.com/iotaledger/identity.rs/security/dependabot/bindings/wasm/package-lock.json/markdown-it/open
Notably, `npm audit` reports no vulnerabilities after this change:
```sh
❯ npm audit
found 0 vulnerabilities 
```
Wasm unit tests and examples pass locally.
The `api-reference.md` docs are still generated as-expected with no changes.
> Update jsdoc-to-markdown to 7.1.1

- examples/account/config.rs
- identity-account/src/account/builder.rs
- identity-account/src/account/config.rs
Removes the `milestone` option from `AccountConfig` and `AccountBuilder` as it is unused in the codebase.
It was previously used or intended to control how often the `Account` state is written to storage:
```rust
/// Save a state snapshot every N actions.
pub(crate) fn milestone(mut self, value: u32) -> Self {
self.milestone = value;
self
}
```
However, the `Account` does not do so, and simply saves the state on `publish` and `fetch_state`.
From this review comment: https://github.com/iotaledger/identity.rs/pull/574#discussion_r800235123
Tests and examples pass, this field was unused.
> Remove unused `Account` milestone option

- identity-core/src/common/one_or_many.rs
This PR removes the `Display` implementation on `OneOrMany`. 
This is non-breaking as our implementation only takes effect whenever `Vec<T>: Display` which cannot happen as `Vec<T>` does not implement display regardless of `T`. See https://doc.rust-lang.org/std/vec/struct.Vec.html#trait-implementations and https://doc.rust-lang.org/std/fmt/trait.Display.html#implementors. 
tests run locally. 
- [] I have commented my code, particularly in hard-to-understand areas
> Remove redundant `impl Display` for `OneOrMany` 

- bindings/wasm/docs/api-reference.md
- bindings/wasm/src/account/update/attach_method_relationships.rs
- bindings/wasm/src/account/update/create_method.rs
- bindings/wasm/src/account/update/create_service.rs
- bindings/wasm/src/account/update/delete_method.rs
- bindings/wasm/src/account/update/delete_service.rs
- bindings/wasm/src/account/update/detach_method_relationships.rs
- bindings/wasm/src/account/wasm_account.rs
- bindings/wasm/src/common/mod.rs
- bindings/wasm/src/common/promise_undefined.rs
- bindings/wasm/src/common/promise_void.rs
Replace return type `Promise<any>` with `Promise<undefined>` for functions that return `JsValue::undefined()`.
Relevant to #574
> Replace Type `Promise<any>` with `Promise<void>`

- .github/workflows/build-and-test.yml
- .github/workflows/clippy.yml
- bindings/wasm/Cargo.toml
- bindings/wasm/src/common/timestamp.rs
- examples/account/multiple_identities.rs
- identity-account/Cargo.toml
- identity-account/src/tests/account.rs
- identity-comm/Cargo.toml
- identity-core/Cargo.toml
- identity-core/src/common/timestamp.rs
- identity-iota/Cargo.toml
- identity/Cargo.toml
Essentially, this changes all `cfg(feature = "wasm")` occurrences to `cfg(all(target_arch = "wasm32", not(target_os = "wasi")))` and removes the `wasm` feature from all crates. Since we only have two occurrences of those in code, most of this applies to various `Cargo.toml`s. The motivation is to enable `Future`s that contain an `Account` to be `Send`. This is not the case in current `dev`, because of `iota_client::Client`. An example that does not compile under current `dev`:
```rust
fn assert_future_send<T: std::future::Future + Send>(_: T) {}
let mut account: Account = AccountBuilder::default()
.create_identity(IdentitySetup::default())
.await?;
assert_future_send(account.update_identity().create_method().apply());
```
which fails with:
```
error: generator cannot be sent between …
```
> Make Wasm support dependent on `target_arch` rather than feature

- bindings/wasm/docs/api-reference.md
- bindings/wasm/src/tangle/config.rs
- identity-iota/src/tangle/client_builder.rs
Exposes the `fallback_to_local_pow` configuration option on the `ClientBuilder` (`Config` for Wasm bindings), which is enabled by default. This allows disabling the behaviour of performing proof-of-work locally when publishing and no nodes support remote PoW.
Aside: we should consider refactoring `Config`, either by
- renaming it `ClientConfig` for clarity, or
- renaming it `ClientBuilder` and adding a `build` method for consistency, or
- replacing it with a duck-typed interface similar to other places in the Wasm bindings (may not be possible due to options with multiple parameters).
- Add `ClientBuilder::fallback_to_local_pow`.
- Add Wasm `Config.setFallbackToLocalPoW`.
Fixes #667.
Wasm tests and examples pass locally.
> Add `Client` fallback to local PoW option

- bindings/wasm/package.json
- bindings/wasm/tests/txm_readme.js
Use mocha to run txm Readme tests in order to use mochas retries functionality.
Forced random failure locally, tests still complete.
CI still passes.
> Enable retries for `txm` tests

- bindings/wasm/examples/src/tests/node/createDiff.js
- bindings/wasm/examples/src/tests/node/createIdentity.js
- bindings/wasm/examples/src/tests/node/createVP.js
- bindings/wasm/examples/src/tests/node/create_vc.js
- bindings/wasm/examples/src/tests/node/manipulateIdentity.js
- bindings/wasm/examples/src/tests/node/merkleKey.js
- bindings/wasm/examples/src/tests/node/privateTangle.js
- bindings/wasm/examples/src/tests/node/resolution.js
- bindings/wasm/examples/src/tests/node/resolveHistory.js
- bindings/wasm/examples/src/tests/node/revokeVC.js
- bindings/wasm/package.json
Use CLI config timeout instead of inline config for Wasm node examples.
CI in this job.
> Simplify test timeout config

- .github/actions/rust/sccache/setup-sccache/action.yml
Use chocolatey instead of scoop to install sccache on windows runners.
> Use chocolatey instead of scoop in CI

- identity-account/src/error.rs
Feature gate the import to make the account compile if the `stronghold` feature is not activated. This shows one of the limitations of our current CI approach, e.g. using `cargo check --all-features`.
n/a
n/a
> Feature gate `StrongholdError` import

- documentation/docs/specs/didcomm/overview.md
- documentation/docs/specs/didcomm/protocols/connection.md
Fixes a link that was pointing to a non-existing feature-discovery document. Replaced the link with the document from the external protocols. 
> Fix link for feature discovery in DIDComm protocols

- bindings/wasm/docs/api-reference.md
- bindings/wasm/src/account/wasm_account/account.rs
- bindings/wasm/src/account/wasm_account/account_builder.rs
- bindings/wasm/src/account/wasm_account/update/attach_method_relationships.rs
- bindings/wasm/src/account/wasm_account/update/create_method.rs
- bindings/wasm/src/account/wasm_account/update/create_service.rs
- bindings/wasm/src/account/wasm_account/update/detach_method_relationships.rs
- bindings/wasm/src/account/wasm_account/update/set_also_known_as.rs
- bindings/wasm/src/account/wasm_account/update/set_controller.rs
- identity-account/src/account/account.rs
- identity-account/src/account/builder.rs
- identity-account/src/account/config.rs
- identity-account/src/identity/identity_updater.rs
- identity-account/src/updates/macros.rs
- identity-account/src/updates/update.rs
- identity-iota/src/tangle/client.rs
- identity-iota/src/tangle/mod.rs
- identity-iota/src/tangle/resolver.rs
- identity-iota/src/tangle/traits.rs
This changes the `Account` and its related structs to be generic over `Arc<Client>` and `Rc<Client>` so that we can use `WasmClient` directly without needing to clone the internal `Client`.
Unfortunately, to make a long story short: we cannot implement a higher kinded type for `Arc`/`Rc` over unsized types, namely `dyn Storage` in the `Account`, due to the lack of [`CoerceUnsized`](https://doc.rust-lang.org/std/ops/trait.CoerceUnsized.html) in stable Rust. 
I believe that without implementing `CoerceUnsized` for whatever `SharedPtrUnsized` trait we come up with, we will be unable to circumvent the type-mismatch error when trying to pass a concrete instance like `Arc<MemStore>`. 
Example:
```rust
AccountSetup::new(
Arc::new(MemStore::new()),
Arc::new(
ClientBuilder::new()
.network(network) …
```
> Generify `Account::client` over `Rc`, `Arc`

- Cargo.toml
- identity-comm/Cargo.toml
- identity-iota/Cargo.toml
- identity/Cargo.toml
- identity/src/lib.rs
Update iota.rs to the latest `dev` commit in order to include the timeout bugfix from iotaledger/iota.rs#848. Previously, the `requet_timeout` builder option was essentially ignored, and since this is the only option we expose, the fix is important to us.
This also comments out the currently unused `identity-comm` crate, because `libjose`'s `rsa = 0.5` dependency requires `zeroize < 1.5`, which is incompatible with the `iota.rs` requirement of (now) `1.5.3` of said crate. `identity-comm` is currently unused and will need a refactor anyway.
Ran a local test (not added to the code base) to make sure the fix works for us:
```rust
#[tokio::test]
async fn test_timeout() {
let client = ClientBuilder::new() …
```
> Update iota.rs to include timeout bugfix

- identity-iota/Cargo.toml
Updates iota.rs to a version where the crate's `zeroize` requirement is below version `1.5`. This is required for RustCrypto dependencies which, at their current version, have a `<1.5` requirement for `zeroize`.
Tested the new version of iota.rs manually in the `feat/identity-actor` branch, where `libp2p` has transitive dependencies on crypto crates with the above-mentioned issue.
> Update iota.rs to lower `zeroize` version requirement

- .github/actions/release/bump-versions/action.yml
Enable `cargo-edit` in `bump-versions` for the Wasm release since we rely on `set-version`.
Also fixes an issue with the version bump, where sub crates where set to the root crate accidentally.
> Install cargo-edit for Wasm releases, fix version bump in CI

- bindings/wasm/package.json
Removes the npm `prepublishOnly` script from the Wasm bindings, which interferes with the release process.
Tested with a dummy release locally.
> Remove Wasm prepublish step

- bindings/stronghold-nodejs/package.json
Sets NAPI.rs default triples to false to prevent double publishes.
Also temporarily disables triples already published.
Can only be tested in CI.
> Fix stronghold triples

- bindings/stronghold-nodejs/js/stronghold.ts
- bindings/stronghold-nodejs/src/account/storage/stronghold.rs
- bindings/wasm/examples-account/src/memory_storage.ts
- bindings/wasm/src/account/storage/traits.rs
- identity-account-storage/src/storage/memstore.rs
- identity-account-storage/src/storage/stronghold.rs
- identity-account-storage/src/storage/traits.rs
Remove the `set_password()` function from the account Storage interface.
fixes issue #733 
> Remove `Storage::set_password`

- .github/actions/publish/publish-stronghold-nodejs/action.yml
- .github/workflows/build-and-test.yml
- .github/workflows/shared-build-and-test-stronghold-nodejs.yml
Use pre-generated dist from build step for stronghold nodejs bindings publish. In the current setup the js dist files do not get included in the package. Weirdly my understanding is the "official" napi.rs CI build has the same problem https://github.com/napi-rs/napi-rs/blob/main/cli/src/new/ci-template.ts.
Partially locally, partially can only be tested in CI.
> Fix Stronghold nodejs binding dist artifact

- bindings/stronghold-nodejs/src/account/storage/stronghold.rs
- bindings/wasm/docs/api-reference.md
- bindings/wasm/src/account/storage/traits.rs
- bindings/wasm/src/account/types/method_secret.rs
- bindings/wasm/src/core/secret_key.rs
- bindings/wasm/src/crypto/key_pair.rs
- bindings/wasm/src/did/wasm_method_data.rs
Fixes a typo where `UInt8Array` is used as a type instead of [`Uint8Array`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array) (note the lowercase `i` in the correct version).
This was causing a Typescript error/warning: `TS2552: Cannot find name 'UInt8Array'. Did you mean 'Uint8Array'?`
Tests and examples pass locally without the above warning.
> Fix `Uint8Array` references

- documentation/docs/advanced/did_messages.mdx
Removes the reference to the `diff_chain` example from the documentation, which removed in #759. This is causing the wiki to break.
```js
Module not found: Error: Can't resolve './../../../bindings/wasm/examples/src/diff_chain.js' in 'C:\Work\iota\identity.rs\documentation\local-wiki\iota-wiki\external\identity.rs\documentation\docs\advanced'
Module not found: Error: Can't resolve './../../../examples/low-level-api/diff_chain.rs' in 'C:\Work\iota\identity.rs\documentation\local-wiki\iota-wiki\external\identity.rs\documentation\docs\advanced'
client (webpack 5.69.1) compiled with 2 errors and 1 warning
```
The documentation runs without error now: `npm run setup && npm run start`
> Remove diff chain example from documentation to fix wiki

- README.md
- bindings/stronghold-nodejs/.license_template
- bindings/stronghold-nodejs/js/stronghold.ts
- bindings/stronghold-nodejs/src/account/storage/stronghold.rs
- bindings/wasm/src/account/wasm_account/account.rs
- bindings/wasm/src/account/wasm_account/account_builder.rs
- examples/account/config.rs
- examples/account/create_did.rs
- examples/account/lazy.rs
- examples/account/manipulate_did.rs
- examples/account/multiple_identities.rs
- examples/account/signing.rs
- examples/account/unchecked.rs
- identity-account-storage/src/storage/stronghold.rs
- identity-account/Cargo.toml
- identity-account/src/account/builder.rs
- identity-account/src/tests/account.rs
Removes `AccountStorage` to simplify passing of `Storage` interfaces to `AccountBuilder`.
Note that there are now two storage setters on `AccountBuilder`: `storage`, which takes any `S: Storage` implementation, and `storage_shared`, which takes `Arc<dyn Storage>`. The reason for this is that I could not find a way to allow a generic parameter to take either `Arc<dyn Storage>` or `impl Storage`. The closest I got was the following:
```rust
pub fn storage<A: Into<Arc<S>>, S: 'static + Storage>(mut self, value: A)
```
Unfortunately the above function does not work when passed an `Arc<storage>`: 
```rust
error[E0282]: type annotations needed
--> examples\account/manipulate_did.rs:34:6
|
34 |     .storage(Arc::new(stronghold))
|      ^^^^^^^ cannot infer type for type parameter `S` declared on …
```
> Remove `AccountStorage`

- bindings/wasm/README.md
Cross-reference Zebra IOTA SDK in WASM bindings docs.
I have a [separate branch](https://github.com/7opf/identity.rs/tree/examples) where I add this link to the examples page (bindings/wasm/examples/README.md) and add the examples page to the site navigation. However, markdown links do not work correctly in the docusaurus site due to the way content is imported so I am submitting this PR until there is a solution.
```sh
cd documentation
npm run setup
npm run start # new section visible on getting started page
```
> added zebra repo link

- bindings/wasm/src/account/wasm_account/account.rs
- bindings/wasm/src/credential/presentation.rs
The return type of creating signed objects in the Account does not match the TypeScript types. 
For example 
```javascript
// Created a signed credential by the issuer. 
const signedVc = await issuer.createSignedCredential(
"#newKey",
unsignedVc,
ProofOptions.default(),
);
``` 
should return a `Credential` according to the method signature: 
```javascript
createSignedCredential(fragment: string, credential: Credential, options: ProofOptions): Promise<Credential>;
```
but the actual return type is `Object` due to a mistake in using `unchecked_into` which should be tested manually every time it's used. 
This PR fixes this issues and the correct type is returned in the following fucntions:
`create_signed_credential`
`create_signed_document`
`create_signed_presentation`
`create_signed_data` …
> Fix Account `create_signed_*` function return types

- .github/workflows/shared-create-hotfix-pr.yml
Temporarily remove the `--release-branch` argument for `github-changelog-generator` to include the PRs to `dev` pushed to `support/wasm-v0.5` in the changelog. This is just to fix the immediate problem for the `wasm-v0.5.1` hotfix release. See #800 for more information.
NOTE: does NOT fix this on `dev` to avoid unforeseen consequences for now, until @eike-hass can review.
See #800
Tested the change locally with `github-changelog-generator`:
```
docker run -w "/github/workspace" -v C:\Work\iota\identity.rs:"/github/workspace" --rm eiha/github-changelog-generator:latest --output ./bindings/wasm/CHANGELOG.md --config-file ./bindin
gs/wasm/.github_changelog_generator --user iotaledger --project identity.rs  --future-release wasm-v0.5.1   --release-branch support/wasm-v0.5 --exclude-tags …
```
> Fix hotfix PR action, remove `release-branch`

- documentation/docs/verifiable_credentials/create.mdx
- documentation/docs/verifiable_credentials/revoke.mdx
- documentation/docs/verifiable_credentials/verifiable_presentations.mdx
Replace outdated links caused by https://github.com/iotaledger/identity.rs/pull/795 in the wiki and use Replits for VC examples.
> Use Replits for VC examples in the wiki

- README.md
Increase the minimum supported Rust version to `1.58`, since the `StorageTestSuite` introduced in #791 uses the `format_args_implicits` feature which was stabilized in `1.58`.
This succeeds:
```
cargo +1.58.0 check --manifest-path bindings/wasm/Cargo.toml --target wasm32-unknown-unknown
```
while this does not:
```
cargo +1.57.0 check --manifest-path bindings/wasm/Cargo.toml --target wasm32-unknown-unknown
```
> Bump MSRV to 1.58

- identity-account-storage/Cargo.toml
- identity-core/Cargo.toml
- identity-iota-core/Cargo.toml
- identity-iota/Cargo.toml
This PR specifies the `iota-crypto` dependencies used by this library to be in the range `0.7` up to (but NOT including) `0.10`.  https://github.com/iotaledger/identity.rs/pull/822 pinned the version to `0.9.1` which was necessary because `0.9.2` introduced a breaking change causing builds to fail. Now `0.9.2` has been yanked from crates.io and pinning is therefore no longer necessary. 
Before #822, we specified version `^0.7` for `iota-crypto` in our crates except for libjose (the reason `0.9.2` still got pulled was because of transitive dependencies (which pinning to `0.9.1` then prevented)), but as #822 demonstrated our library also worked with `0.9.1` and I have also tested with `0.8`. Hence the question is do we use the range specified in this PR, or go back to `^0.7` or use `^0.9` …
> Unpin iota-crypto version

- .github/Dockerfile.alpine
- .github/workflows/build-and-test.yml
- .github/workflows/shared-build-and-test-stronghold-nodejs.yml
- bindings/stronghold-nodejs/package.json
- identity-account-storage/src/storage/stronghold.rs
Use an Alpine container ([`rust:1-alpine`](https://hub.docker.com/layers/rust/library/rust/1-alpine/images/sha256-e1ddd35b6a802ac8587f8fbc34ce752be20b5c116df2b2f1a90488f0bc3bd439?context=explore)) to build and test the Stronghold napi bindings. Re-enables the musl target.
We could pin to e.g. `rust:1.60-alpine` but the current Rust step pulls in the latest stable version anyway, so `rust:1-alpine` matches that behaviour.
Fixes #837
Works locally and passes in GitHub Actions: https://github.com/iotaledger/identity.rs/actions/runs/2283180473
> Fix Stronghold bindings build for musl

- bindings/wasm/src/account/wasm_account/account.rs
- identity-account/src/account/account.rs
- identity-account/src/tests/account.rs
In the account, after publication, we have created a version of the internal document with a signature, but we currently discard it. Instead, we should set it internally, so `Account::document` returns this document with a valid signature.
n/a, came up on Discord.
A test was added to check the behavior.
> After publication, overwrite `Account` document with published one

- bindings/stronghold-nodejs/src/error.rs
- bindings/wasm/src/account/storage/traits.rs
- bindings/wasm/src/error.rs
Improve the conversion of errors in Napi when going from Rust to JS. This simply includes the entire error chain in the error string, which is necessary because the new stronghold errors do not include the source errors in their string representation, as per our error guidelines.
As an example, when opening a stronghold with an incorrect password:
**Current dev**
```
Error: snapshot operation `read` on path `test_strongholds/test.stronghodl` failed
```
**This PR**
```
Error: snapshot operation `read` on path `test_strongholds/test.stronghodl` failed. Caused by: Inner error occured(corrupted file: Decryption failed: error in algorithm XCHACHA20-POLY1305).
```
For formatting, the Napi code uses a modified version of the `error_chain_fmt` function from Wasm.
[Our error …
> Improve Napi-Wasm error conversion

- identity/Cargo.toml
Activate these features by default, as these are the recommended ways to use the framework.
n/a
None.
> Activate `account`, `stronghold` and `send-sync-storage` features by default

- bindings/wasm/docs/api-reference.md
- bindings/wasm/src/did/wasm_did_url.rs
- identity-did/Cargo.toml
- identity-did/src/did/did_url.rs
Changes `DIDUrl::join` to borrow `self` instead of consuming it, as discussed in #805.
Technically a breaking change since explicit functions calls with e.g. `DIDUrl::join(url, "blah")` would need to change to e.g. `DIDUrl::join(&url, "blah")`.
See discussion #805.
Minor change, existing unit tests cover it.
> Change `DIDUrl::join` to borrow self

- bindings/wasm/package-lock.json
- bindings/wasm/src/account/types/cek_algorithm.rs
- bindings/wasm/src/account/types/encryption_algorithm.rs
- identity-account-storage/Cargo.toml
- identity-account-storage/src/storage/memstore.rs
- identity-account-storage/src/storage/stronghold.rs
- identity-account-storage/src/storage/test_suite.rs
- identity-account-storage/src/stronghold/tests.rs
- identity-account-storage/src/types/encryption/cek_algorithm.rs
- identity-account-storage/src/types/encryption/encryption_algorithm.rs
Implements `ECDH-ES+A256KW` in the `Storage` encryption API, for use in `DIDComm`.
Part of #841
`StorageTestSuite` was modified to also test the newly added `CekAlgorithm`.
> Implement `ECDH-ES+A256KW` for `Storage` encryption

- examples/account/revoke_vc.rs
Fixes a small typo in the `revoke_vc.rs` example. 
Just a typo fix in a comment so no need to test this. 
> Fixed typo "verfiers" -> "verifiers" in `examples/account/revoke_vc.rs`

- .github/actions/publish/publish-rust/action.yml
Wraps the `dry-run` input parameter in a string for the comparison to work. Stupid boolean logic inference.
Part of #869.
They haven't been. We test in production.
> Fix Rust publish boolean parameter

- .github/actions/publish/publish-rust/action.yml
- examples/Cargo.toml
Bump examples to `0.6.0` to try prevent `cargo-release` from needing a git username and email.
Fix shell comparison. Remove bash syntax.
> Bump examples version

- .github/actions/release/bump-versions/action.yml
Also bump the `examples/Cargo.toml` version when bumping the version on other Rust crates.
This is because the publish action uses `cargo release` which attempts (and fails) to bump the `examples/Cargo.toml` version itself, while `cargo workspaces` which we use in the release action ignores the `examples` when versioning (rightly so).
This PR uses the same code for bumping the Stronghold bindings version, so it should work just fine.
"We test in production":tm:.
> Bump examples version in GitHub Actions

- identity_core/src/crypto/proof/jcs_ed25519.rs
- identity_core/tests/fixtures/jcs_ed25519/test_vector_1.json
- identity_core/tests/fixtures/jcs_ed25519/test_vector_2.json
This PR changes the JCSEd25519 test to deserialize a JSON representation of the official test vectors instead of including their Rust representation with the `include!` macro. This is necessary in order to migrate to [cargo-license-template](https://crates.io/crates/cargo-license-template/0.1.2) as that crate scans all `.rs` files for a license header. A valid alternative would be to rename the included file to have another file extension (like `.in` for instance), but the include macro's [official documentation](https://doc.rust-lang.org/std/macro.include.html) states: 
> Using this macro is often a bad idea, because if the file is parsed as an expression, it is going to be placed in the surrounding code unhygienically. This could result in variables or functions being different from …
> Avoid the include! macro

- identity_account/Cargo.toml
- identity_account/src/account/account.rs
- identity_account_storage/src/storage/memstore.rs
- identity_account_storage/src/storage/traits.rs
- identity_iota/Cargo.toml
- identity_iota/src/lib.rs
- identity_iota_client/Cargo.toml
- identity_iota_client/src/credential/credential_validator.rs
- identity_iota_core/src/document/iota_document.rs
Fixes the following commands not suceeding:
```
cargo check --no-default-features -p identity_iota
cargo check --no-default-features -p identity_iota_client
cargo check --no-default-features -p identity_account
cargo check --no-default-features -p identity_account_storage
```
- The `revocation-bitmap` feature flag was not properly gating all types and functions in `identity_iota_client` and `identity_account`.
- The `encryption` feature flag was not properly gating all types and functions in `identity_account_storage` and `identity_account`.
iota.rs requires either the `async` or `sync` feature to be activated, so the `async` feature was removed and the `async` feature of iota.rs is now activated unconditionally.
Code was moved to modules which can be feature-gated with a single …
> Fix cargo check with `--no-default-features`

- identity_agent/Cargo.toml
- identity_agent/src/tests/handler.rs
Fixes an agent test that appears to be brittle on some systems or platforms or situations - it's unclear what exactly the problem is. 
The order of addresses and addresses themselves returned from `Agent::addresses` aren't the same across executions, so the occassional failures appear to come from times when the first address that is picked isn't dialable.
This is fixed by adding all addresses for an agent, which allows libp2p to attempt a dial for all of them.
Also fixes the crate description to match the README.
n/a
The test was run on the affected system and appears to work consistently now.
> Fix brittle agent test

- .github/workflows/test-docs-build.yml
- identity_iota_client/README.md
Build Rust documentation in CI to catch broken links early. The new check is relatively fast at ~5 minutes, so should not slow down the overall CI, especially when run in parallel with much larger jobs.
- Successful CI run: https://github.com/iotaledger/identity.rs/runs/7255904825?check_suite_focus=true
- **Failed CI run** (to show it catches broken intra-doc links, even from a README.md file): https://github.com/iotaledger/identity.rs/runs/7256033459?check_suite_focus=true
To test locally, change one of the documentation links in a Rust file to be incorrect. 
Then run:
```bash
RUSTDOCFLAGS="-D warnings" cargo doc --all-features --no-deps --workspace
```
It should print an error similar to the one below and exit with code 1:
```rust
error: unresolved link to …
```
> Add Rust documentation check to GitHub Actions

- bindings/wasm/docs/api-reference.md
- bindings/wasm/src/account/wasm_account/update/create_service.rs
- bindings/wasm/src/did/wasm_document.rs
- bindings/wasm/src/did/wasm_service.rs
- bindings/wasm/tests/account.ts
- bindings/wasm/tests/document.ts
- identity_account/src/tests/updates.rs
- identity_account/src/updates/update.rs
- identity_core/src/common/key_comparable.rs
- identity_core/src/common/one_or_set.rs
- identity_core/src/common/ordered_set.rs
- identity_credential/src/validator/credential_validator.rs
- identity_credential/src/validator/validator_document.rs
- identity_did/src/diff/diff_service.rs
- identity_did/src/revocation/bitmap.rs
- identity_did/src/service/builder.rs
- identity_did/src/service/service.rs
Changes the `Service.type` field from `String` to `OneOrSet<String>` (Wasm `string | string[]`) to match the [W3C DID specification](https://www.w3.org/TR/did-core/#service-properties).
> `type` A [string](https://infra.spec.whatwg.org/#string) or a [set](https://infra.spec.whatwg.org/#ordered-set) of [strings](https://infra.spec.whatwg.org/#string).
- Change `Service` `type` field from `String` to `OneOrSet<String>`.
- Impl `KeyComparable` for standard types, so they can be used with `OneOrSet`.
Addresses second part of #447, previously missed.
See https://github.com/iotaledger/identity.rs/issues/447#issuecomment-1181654228
New unit tests pass for both `account.update_identity().create_service()` and `document.insert_service()`, including in Wasm bindings, and also tested manually with …
> Change `Service` `type` field to allow sets

- identity_did/src/did/did.rs
Fixes an infinite recursion when comparing `CoreDID`s. The following example currently causes a stack overflow:
```rust
let example1 = CoreDID::parse("did:example:0x0").unwrap();
let example2 = CoreDID::parse("did:example:0x1").unwrap();
println!("{}", example1 == &example2);
```
The Rust compiler ends up effectively calling:
```rust
<CoreDID as PartialEq<&CoreDID>>::eq(&example1, &&example2)
```
which recurses infinitely. The implementation is:
```rust
impl PartialEq<&CoreDID> for CoreDID {
fn eq(&self, other: &&CoreDID) -> bool {
self == other
}
}
```
Two options for fixing the situation: 1) Using `*other` or 2) removing the impl. We don't use this implementation anywhere, and since this impl has been around for 9 months without anyone running into the problem, there's a good chance no …
> Fix stack overflow in `CoreDID` `PartialEq` impl

- identity_stardust/Cargo.toml
- identity_stardust/examples/create_did.rs
- identity_stardust/src/did/mod.rs
- identity_stardust/src/did/stardust_did.rs
- identity_stardust/src/document/mod.rs
- identity_stardust/src/document/stardust_document.rs
- identity_stardust/src/error.rs
- identity_stardust/src/lib.rs
- identity_stardust/src/state_metadata/document.rs
Integrates `StardustDocument` with `StardustDID` introduced in #949. Also simplifies the public API of `StardustDID` somewhat to reduce the work needed for the future Wasm bindings. The `"iota-client"` feature-gate is to prevent potential compilation errors in the future, and would be good to have in general.
- Add `"iota-client"` feature to `identity_stardust`.
- Change `StardustDocument::new` to take `NetworkName`.
- Make `StardustDID` functions `check_method`, `check_method_id`, and `check_network` private.
- Move `StardustDocument::did_from_block` to `StardustDID::from_block`.
- Rename and feature-gate `StardustDocument::deserialize_from_output` to `unpack_from_output`.
- Remove `StardustDocument::placeholder_did`.
- Remove `StardustDID::with_network_name` - it had a bug where setting …
> Feature-gate `iota-client` dependency, integrate `StardustDID`

- .github/workflows/build-and-test.yml
Changes the `cargo` parameters in CI workflows to use `all-features` consistently. This prevents recompilations when running the tests and examples.
Build:
> Compiling examples v0.6.0 (D:\a\[identity.rs](http://identity.rs/)\[identity.rs](http://identity.rs/)\examples)
>     Finished release [optimized] target(s) in 28m 12s
Run tests:
> Compiling examples v0.6.0 (D:\a\[identity.rs](http://identity.rs/)\[identity.rs](http://identity.rs/)\examples)
>     Finished release [optimized] target(s) in 23m 23s
>      Running unittests src\[lib.rs](http://lib.rs/) (target\release\deps\identity_diff-f13010726bc18707.exe)
https://github.com/iotaledger/identity.rs/runs/7516322686?check_suite_focus=true
Build:
>    Compiling examples v0.6.0 (D:\a\identity.rs\identity.rs\examples)
>     Finished release …
> Change CI params to use all-features consistently

- bindings/wasm/Cargo.toml
- examples/0_basic/0_create_did.rs
- examples/0_basic/1_update_did.rs
- examples/0_basic/2_resolve_did.rs
- examples/0_basic/3_deactivate_did.rs
- examples/0_basic/4_delete_did.rs
- examples/1_advanced/0_did_controls_did.rs
- examples/1_advanced/1_did_issues_nft.rs
- examples/1_advanced/2_nft_owns_did.rs
- examples/1_advanced/3_did_issues_tokens.rs
- examples/1_advanced/4_key_exchange.rs
- examples/Cargo.toml
- identity_stardust/Cargo.toml
- identity_stardust/src/error.rs
- identity_stardust/src/lib.rs
To avoid version clashes due to different versions of `bee-block` and `iota-client::block`, this PR changes the reexport of `bee-block` to use `iota_client::block` in general, and only fall back to `bee-block` for bindings.
Update to new `iota-client` version, since the older version prevented a successfull build due to a version clash.
n/a
Local build succeeds.
> Reexport `bee-block` from `iota-client`

- .github/workflows/build-and-test.yml
- Use `cargo metadata` instead of `cargo read-manifest` for CI, since the former is deprecated.
- Improve performance slightly by invoking compiled examples directly rather than through cargo, which needs to acquire the build lock, which might be a problem when used with `parallel`.
n/a
n/a
> Remove deprecated `cargo read-manifest`

- identity_iota_client/Cargo.toml
With the release of `tokio 1.21.0` the wasm bindings no longer compile. This PR fixes that. 
Until now the `identity_iota_client` crate depended on `iota-client` with the `async` feature which brings in `tokio` with the `rt-multi-thread` feature which now no longer compiles when targeting `wasm32-unknown-unknown`. 
With this PR the `iota-client` dependency will only be compiled with the `async` feature when the target family is NOT `wasm`. The `tokio` namespace is only present in `iota-client: 1.3.0` when the `wasm` feature is NOT or certain other features (which we do not use) such as `mqtt` is, hence this PR should not break any functionality from `iota-client: 1.3.0` that the identity.rs bindings currently relies on. 
Describe …
> Fix broken wasm bindings compilation

- identity_agent/Cargo.toml
- identity_agent/benches/didcomm.rs
- identity_agent/src/didcomm/agent.rs
- identity_agent/src/tests/mod.rs
Remove direct dependency of the agent on legacy crates. These were only used for the proof-of-concept type `DidCommAgentIdentity` so removing them is rather straightforward.
Note that this was branched off of the currently broken `epic/stardust-refactor` branch, so I don't expect CI to pass and I will merge after reviewer approval.
part of #908
Ran agent tests successfully.
> Stardust Refactor (Part 3)

- bindings/wasm/Cargo.toml
- bindings/wasm/src/error.rs
- bindings/wasm/src/resolver/mixed_resolver.rs
- identity_iota/Cargo.toml
- identity_iota/src/lib.rs
Feature gate the resolver in `identity_iota`, and add client extension traits to the prelude.
Follow up to #1000.
`cargo check`
> Feature-gate `Resolver`

- bindings/wasm/src/iota/identity_client_ext.rs
The `IRent` structure in JS uses camelCase while the Rust code in `new_did_output` expects snake_case. This fixes it by deserializing to `RentStructureBuilder` which supports both casings. Thanks to @cycraig for finding the culprit.
n/a
Running an example that uses `newDidOutput` and passes an `IRent` object.
> Support case insensitive serialization of `RentStructure`

- .github/workflows/format.yml
- .license_template_ignore
- bindings/wasm/src/iota/iota_verification_method.rs
- examples/utils/utils.rs
- rustfmt.toml
Use [cargo-license-template](https://crates.io/crates/cargo-license-template) as a replacement for the removed `license_template_path` feature of `rustfmt`.
Note that running `cargo-license-template` in the root of the workspace checks all sub-directories, including the Wasm and Stronghold bindings.
Fixes #921.
```
cargo install -f cargo-license-template
cargo license-template --template .license_template --ignore .license_template_ignore --verbose
```
Passes in CI too: https://github.com/iotaledger/identity.rs/actions/runs/3060562925/jobs/4939227569
> Use cargo-license-template

- identity_agent/Cargo.toml
- identity_agent/benches/agent.rs
- identity_agent/src/tests/handler.rs
- identity_agent/src/tests/remote_account/handler.rs
- identity_agent/src/tests/remote_account/requests.rs
- identity_agent/src/tests/remote_account/tests.rs
Pin the `identity_account` and `identity_iota_core_legacy` dev-dependencies of the agent to the crates versions rather than paths.
This is in attempt to fix publishing of the agent crate with cargo-release, which apparently verifies that the dev-dependencies are on crates.io.
```
[2022-09-16T16:41:48Z INFO  cargo_release::release] Publishing identity_agent
Updating crates.io index
Packaging identity_agent v0.7.0-alpha.1 (/home/runner/work/identity.rs/identity.rs/identity_agent)
Verifying identity_agent v0.7.0-alpha.1 (/home/runner/work/identity.rs/identity.rs/identity_agent)
error: failed to verify package tarball
Error: failed to verify package tarball
Caused by:
no matching package named `identity_iota_core_legacy` found
location searched: registry `crates-io`
required by package …
```
> Pin agent dev-dependencies to crates versions

- Cargo.toml
- identity_iota/Cargo.toml
- identity_iota/src/lib.rs
Remove the reexport of the agent from `identity_iota` due to causing issues during publishing. The issues are caused by the agent's dev-dependency on `identity_account` and `identity_iota_core_legacy`, the latter of which does not exist on crates.io, which appears to be a requirement for publishing.
We'll address theses issues and include the agent in `identity_iota` again, eventually.
n/a
`cargo check`
> Remove `identity_agent` reexport

- .github/actions/release/bump-versions/action.yml
- bindings/stronghold-nodejs/Cargo.lock
- bindings/stronghold-nodejs/Cargo.toml
- identity_account/Cargo.toml
- identity_account_storage/Cargo.toml
- identity_iota_client_legacy/Cargo.toml
- identity_iota_core_legacy/Cargo.toml
- Bump versions of legacy crates for consistency.
- Bump them in the next release as part of the workflow.
- Note that stronghold-nodejs crate versions were updated but not explicitly added to `action.yml`, because they are already bumped as part of that script, it just bumped to the same version in the last release because those crates weren't bumped earlier. Since they are bumped before that step now, that should work out on the next run.
n/a
`cargo check`
> Bump versions of legacy crates

- bindings/wasm/src/did/wasm_core_document.rs
- bindings/wasm/src/iota/iota_document.rs
- identity_account/src/tests/account.rs
- identity_account/src/tests/updates.rs
- identity_credential/src/validator/credential_validator.rs
- identity_credential/src/validator/presentation_validator.rs
- identity_did/src/document/core_document.rs
- identity_iota_client_legacy/src/tangle/resolver.rs
- identity_iota_core/src/document/iota_document.rs
- identity_iota_core_legacy/src/document/iota_document.rs
Add an optional scope parameter to the method getter on DID Document implementations to allow iterating over particular verification relationship fields.
`fixes issue #989`
> Expose iteration over verification relationship fields

- .github/workflows/build-and-test.yml
Remove the step to run `examples_legacy` from GitHub Actions, since they (along with the other legacy projects) are no longer built in CI and are intended to be removed.
CI should pass now.
> Remove legacy example tests from CI

- .github/workflows/build-and-test.yml
Checks each crate in the workspace can compile with their default features and without any features enabled at all.
Each crate must be compiled individually since some enable features on others.
Tested the commands locally in WSL.
> Check default and no-default-features in CI

- bindings/wasm/docs/api-reference.md
- bindings/wasm/src/iota/identity_client_ext.rs
- bindings/wasm/src/iota/iota_document.rs
Small changes to the `aliasOutput` type in `IotaDocument.unpackFromOutput` added in #1023 from `any` (`JsValue`) to `IAliasOutput`.
Compiles locally, tests pass.
> Fix `IotaDocument.unpackFromOutput` parameter type

- documentation/docusaurus.config.js
With version 3 of the wiki we don't need to separate docs that aren't part of the same network. And as this is shimmer content it will be hosted under /shimmer/identity.rs
> Remove docs version info

- bindings/wasm/Cargo.toml
- bindings/wasm/docs/api-reference.md
- bindings/wasm/package-lock.json
- bindings/wasm/package.json
- bindings/wasm/src/error.rs
- bindings/wasm/src/iota/identity_client_ext.rs
- bindings/wasm/src/iota/iota_did.rs
- bindings/wasm/src/iota/iota_document.rs
- examples/1_advanced/1_did_issues_nft.rs
- examples/1_advanced/2_nft_owns_did.rs
- examples/1_advanced/3_did_issues_tokens.rs
- examples/1_advanced/5_alias_output_history.rs
- examples/Cargo.toml
- identity_diff/src/option.rs
- identity_iota_core/Cargo.toml
- identity_iota_core/src/client/iota_client.rs
- identity_iota_core/src/document/iota_document.rs
- identity_iota_core/src/lib.rs
Updates the `iota-client 2.0.1-rc.3` dependency, replaces the `bee-block` dependency with `iota_types` and updates the `primitive-types` dependency.  
Runs locally under `cargo test --all-features` and `cargo test --no-default-features`.  
> Update iota client 2.0.1 rc.3

- bindings/wasm/build/replace_paths.js
- bindings/wasm/docs/api-reference.md
- bindings/wasm/lib/iota_identity_client.ts
- bindings/wasm/lib/tsconfig.json
- bindings/wasm/lib/tsconfig.web.json
- bindings/wasm/package-lock.json
- bindings/wasm/package.json
- bindings/wasm/tsconfig.json
Some imports were replaced by the relative paths in `tsconfig.json` using [tsc-alias](https://www.npmjs.com/package/tsc-alias). These relative paths work fine locally, but not in the npm package.
For example, the path `"../node_modules/@iota/iota-client-wasm/node"` doesn't exist when importing the identity package from npm. and it should be `"@iota/iota-client-wasm/node"` instead.
To fix this, the `tsc-alias` is removed and replaced with a custom script that will replace the aliases defined in the `tsconfig.json` file with the path (only for `.ts` and `.js` files). If two paths are defined in the `tsconfig` file, the second path is used as a replacement for the alias. 
This allows to use the first path for local compilation and the second one to be used for the package.
Add an `x` to the …
> Fix unresolved import in TS artifacts

- examples/0_basic/1_update_did.rs
- examples/0_basic/2_resolve_did.rs
- examples/0_basic/3_deactivate_did.rs
- examples/0_basic/4_delete_did.rs
- examples/0_basic/5_create_vc.rs
- examples/0_basic/6_create_vp.rs
- examples/1_advanced/0_did_controls_did.rs
- examples/1_advanced/1_did_issues_nft.rs
- examples/1_advanced/2_nft_owns_did.rs
- examples/1_advanced/3_did_issues_tokens.rs
- examples/1_advanced/5_alias_output_history.rs
- examples/1_advanced/6_custom_resolution.rs
- examples/Cargo.toml
- examples/utils/utils.rs
- identity_core/src/crypto/proof/proof.rs
- libjose/src/jwk/key.rs
- libjose/src/utils/crypto/concat_kdf.rs
- libjose/tests/rfc.rs
Add missing verifiable credentials and verifiable presentations examples
#1060
> Add v. credentials and presentations examples

- bindings/wasm/Cargo.toml
- examples/Cargo.toml
- identity_iota_core/Cargo.toml
This is a temporary fix for breaking builds. Should be removed/rolled back once `iota-client 2.0.1-rc.4` is released. 
Runs under `cargo build --all-features`, `cargo check --examples` and the TS bindings also build. 
> Temporarily pin `iota-types` version

- bindings/wasm/examples/README.md
- bindings/wasm/examples/src/0_basic/7_revoke_vc.ts
- bindings/wasm/examples/src/main.ts
- bindings/wasm/examples/src/tests/7_revoke_vc.ts
- examples/0_basic/7_revoke_vc.rs
- examples/Cargo.toml
- examples/README.md
Add example for revoking verifiable credentials in Rust and Wasm.
#1060 
> Add revocation examples

- examples/Cargo.toml
- identity_iota_core/src/state_metadata/document.rs
- identity_iota_core/src/state_metadata/mod.rs
We currently get warnings that `StateMetadataDocument::{into_iota_document,unpack}` are unused when running `cargo check --no-default-features`.
This PR makes `StateMetadata` public to get rid of those warnings. Another approach would have been to feature-gate everything state metadata related behind the `client` feature. The reasoning for making it public is that `StateMetadata` can be used with clients other than `iota-client` and there's no inherent reason why it has to be tied to that specific client. We may also want to use it from the Wasm bindings without adding a dependency to iota-client in order to decode the state metadata of an Alias Output resolved by, say, `iota.js`.
`Eq` was also derived for `StateMetadataDocument` to satisfy a clippy lint.
n/a
Add an `x` to the boxes that …
> Make `StateMetadataDocument` public

- bindings/wasm/README.md
- bindings/wasm/examples/src/0_basic/0_create_did.ts
- bindings/wasm/examples/src/0_basic/1_update_did.ts
- bindings/wasm/examples/src/0_basic/2_resolve_did.ts
- bindings/wasm/examples/src/0_basic/3_deactivate_did.ts
- bindings/wasm/examples/src/0_basic/4_delete_did.ts
- bindings/wasm/examples/src/0_basic/5_create_vc.ts
- bindings/wasm/examples/src/0_basic/6_create_vp.ts
- bindings/wasm/examples/src/0_basic/7_revoke_vc.ts
- bindings/wasm/examples/src/1_advanced/0_did_controls_did.ts
- bindings/wasm/examples/src/1_advanced/1_did_issues_nft.ts
- bindings/wasm/examples/src/1_advanced/2_nft_owns_did.ts
- bindings/wasm/examples/src/1_advanced/3_did_issues_tokens.ts
- bindings/wasm/examples/src/1_advanced/4_key_exchange.ts
- bindings/wasm/examples/src/1_advanced/5_custom_resolution.ts
- bindings/wasm/examples/src/util.ts
- documentation/docs/concepts/decentralized_identifiers/resolve.mdx
Updates examples and documentation to use the official client-wasm bindings. 
> Use official client-wasm dependency in examples

- bindings/wasm/build/lints.js
This removes the `lintPtrNullWithoutFree(content)` function which is used when building the Wasm/TS/JS bindings.
The lint was introduced to catch generated code that nulls out Wasm pointers without de-registering the finalizer (we build our bindings with the `--weak-refs` flag for automatic garbage collection see [this section of the wasm-bindgen reference](https://rustwasm.github.io/wasm-bindgen/reference/weak-references.html)). 
As of [wasm-bindgen PR #3117](https://github.com/rustwasm/wasm-bindgen/pull/3117)  which is included in version `0.2.84` of `wasm-bindgen` such problematic code is no longer generated hence the lint is no longer needed. 
Tested building this code (in `wasm_core_did.rs`) 
```
impl WasmCoreDID {
//.. 
/// Swaps the contents and consumes `other`.  
#[wasm_bindgen] …
```
> Remove outdated lint

- .github/actions/publish/publish-rust/action.yml
- .github/actions/release/bump-versions/action.yml
- .github/actions/rust/rust-setup/action.yml
- .github/actions/rust/sccache/setup-sccache/action.yml
- .github/actions/rust/sccache/stop-sccache/action.yml
- .github/workflows/audit.yml
- .github/workflows/build-and-test.yml
- .github/workflows/clippy.yml
- .github/workflows/format.yml
- .github/workflows/rust-automatic-release-and-publish.yml
- .github/workflows/rust-publish-to-crates.yml
- .github/workflows/shared-build-and-test-stronghold-nodejs.yml
- .github/workflows/shared-build-wasm.yml
- .github/workflows/shared-create-dev-release-pr.yml
- .github/workflows/shared-create-hotfix-pr.yml
- .github/workflows/shared-create-main-release-pr.yml
- .github/workflows/shared-release.yml
- .github/workflows/test-docs-build.yml
- .github/workflows/wasm-automatic-release-and-publish.yml
Central workflow actions we use setup our rust tooling in CI have been unmaintained for a while. We need to move away from them since some of their dependencies and assumptions have bee deprecated by GitHub and might cease to work in the future. 
The two noteworthy deprecations are: 
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
Some alternatives (and general dissatisfaction) have been discussed in issues in the actions repositories:
https://github.com/actions-rs/toolchain/issues/221
https://github.com/actions-rs/toolchain/issues/219
Note:
We still need to find a replacement for …
> Replace deprecated workflow functions

- examples/Cargo.toml
Move the `release` flag of `cargo-release` to its proper place, i.e. `[package.metadata.release]`, according to https://github.com/crate-ci/cargo-release/blob/v0.21.4/docs/reference.md.
n/a
n/a
> Move release config flag

- identity_storage/Cargo.toml
- identity_storage/src/error.rs
- identity_storage/src/key_id_storage/key_id_storage.rs
- identity_storage/src/key_id_storage/key_id_storage_error.rs
- identity_storage/src/key_id_storage/memstore.rs
- identity_storage/src/key_id_storage/method_digest.rs
- identity_storage/src/key_id_storage/mod.rs
- identity_storage/src/key_id_storage/storage.rs
- identity_storage/src/key_storage/jwk_storage.rs
- identity_storage/src/key_storage/key_storage_error.rs
- identity_storage/src/key_storage/memstore.rs
- identity_storage/src/lib.rs
Add the `KeyIdStorage` trait as a way for saving `KeyId`s of verification method materials by introducing `MethodDigest` that takes a `VerificationMethod`.  This is an implementation of the issue https://github.com/iotaledger/identity.rs/issues/1126 with the difference that `IdentityStorage` is named here as `KeyIdStorage` (to be discussed). 
`KeyStorageError` is now refactored as generic `StorageError` for both `KeyStorage` and `KeyIdStorage`. 
`fixes issue #1126`.
> implement `KeyIdStorage` in Rust

- identity_core/src/common/mod.rs
- identity_core/src/common/single_struct_error.rs
- identity_jose/Cargo.toml
- identity_jose/src/jws/custom_verification/error.rs
- identity_storage/src/key_id_storage/key_id_storage_error.rs
- identity_storage/src/key_id_storage/method_digest.rs
- identity_storage/src/key_storage/key_storage_error.rs
- identity_storage/src/lib.rs
This PR renames and moves `StorageError` to `identity_core` so that it may be used in more contexts where the [single struct error design pattern](https://nrc.github.io/error-docs/error-design/error-type-design.html#single-struct-style) is desirable. A first example of this is the additional use in `SignatureVerificationError` in `identity_jose`. 
Also uses `Debug + Display` as trait bounds directly on the error kind and removes the `ErrorKind` trait in order to reuse existing traits and not introduce too many new traits. 
Finally I added the possibility to add recovery data to the generic error. This is not needed as of now, but might become useful in the future. This required an additional generic parameter which is the unit type `()` by default. Since we always type alias errors built …
> Adapt StorageError to be more generic

- identity_iota_client/Cargo.toml
Fixes the Wasm build for `0.6`. It is unclear why it broke in the first place, but the build failed due to the `curl-p` feature not being activated for `iota-crypto`, so it was added explicitly.
n/a
> Fix 0.6 Wasm build

- identity_credential/src/revocation/document_ext.rs
- identity_storage/Cargo.toml
- identity_storage/src/storage/tests/credential_validation.rs
- identity_storage/src/storage/tests/test_utils.rs
Port every test from the current `identity_credential::validator::credential_validator` module except `test_full_validation_invalid_structure` since it is much harder to get wrong with JWS-based credentials than with the legacy ones.
Tests are executed for both `CoreDocument` and `IotaDocument` with the exception of the revocation functions, since `IotaDocument` does not implement `RevocationDocumentExt` (it exposes those methods inherently) making a generic test harder to write.
part of #1103
`cargo test`
> Test `JWTCredentialValidator`

- bindings/wasm/src/verification/wasm_method_type.rs
- documentation/docs/specs/did/iota_did_method_spec.mdx
- identity_storage/src/key_storage/memstore.rs
- identity_verification/src/verification_method/method.rs
- identity_verification/src/verification_method/method_type.rs
Update the method spec and JWK method type.
- Method spec previously incorrectly allowed for a network name to be of length 0. If present, its length must be > 0. This is already correctly checked in code. The code also allows for the presence of digits in the network name and the spec was updated to match that, too.
- Use `JsonWebKey` as the method type according to https://github.com/w3c/vc-jwt/issues/83, as it is the best recommendation we have for now.
n/a
None.
> Update method spec and JWK method type

- bindings/wasm/docs/api-reference.md
- bindings/wasm/src/resolver/wasm_resolver.rs
- bindings/wasm/tests/resolver.ts
- identity_resolver/src/error.rs
- identity_resolver/src/resolution/resolver.rs
- identity_resolver/src/resolution/tests/mod.rs
- identity_resolver/src/resolution/tests/resolution.rs
Allow resolving multiple DID documents in parallel.
The method first removes any did duplicates before resolving, since duplicates can be common, for example if a verificable presentation has multiple credentials issued by the same DID. The order is then re-established for convenience and to avoid the need of filtering to retrieve the correct DID. To allow this, the documents must be clonable. 
https://github.com/iotaledger/identity.rs/pull/1183
> Add `resolve_multiple` to Resolver.

- bindings/wasm/src/common/types.rs
- bindings/wasm/src/credential/jwt_credential_validation/unknown_credential.rs
- bindings/wasm/src/credential/jwt_presentation/jwt_presentation_builder.rs
- bindings/wasm/tests/credentials.ts
- bindings/wasm/tests/storage.ts
Use `Record` type for unknown credentials in Wasm and finish an incomplete test for `IotaDocument`.
part of #1103 
`npm run test:unit:node`
> Use `Record` type for unknown credentials in Wasm

- bindings/wasm/docs/api-reference.md
- bindings/wasm/examples/src/0_basic/6_create_vp.ts
- bindings/wasm/examples/src/0_basic/7_revoke_vc.ts
- bindings/wasm/src/credential/jwt_presentation/mod.rs
- bindings/wasm/src/credential/jwt_presentation/presentation.rs
- bindings/wasm/src/credential/jwt_presentation/presentation_builder.rs
- bindings/wasm/src/credential/jwt_presentation_validation/decoded_jwt_presentation.rs
- bindings/wasm/src/credential/jwt_presentation_validation/jwt_presentation_validator.rs
- bindings/wasm/src/did/wasm_core_document.rs
- bindings/wasm/src/iota/iota_document.rs
- bindings/wasm/tests/credentials.ts
- bindings/wasm/tests/storage.ts
- examples/0_basic/6_create_vp.rs
- identity_credential/src/credential/credential.rs
- identity_credential/src/credential/policy.rs
- identity_credential/src/error.rs
- identity_credential/src/presentation/jwt_serialization.rs
- identity_credential/src/presentation/mod.rs
- identity_credential/src/presentation/presentation.rs
- identity_credential/src/presentation/presentation_builder.rs
- identity_credential/src/validator/vc_jwt_validation/error.rs
- identity_credential/src/validator/vp_jwt_validation/decoded_jwt_presentation.rs
- identity_credential/src/validator/vp_jwt_validation/error.rs
- identity_credential/src/validator/vp_jwt_validation/jwt_presentation_validation_options.rs
- identity_credential/src/validator/vp_jwt_validation/jwt_presentation_validator.rs
- identity_storage/src/storage/jwk_document_ext.rs
- identity_storage/src/storage/tests/presentation_validation.rs
Since `JwtPrsentation` is not generic and not tied to JWT, it's now renamed to `Presentation`.
> Rename `JwtPresentation` to `Presentation`

- bindings/wasm/lib/iota_identity_client.ts
- bindings/wasm/src/iota/iota_did.rs
- bindings/wasm/src/iota/iota_document.rs
- bindings/wasm/src/iota/iota_document_metadata.rs
- bindings/wasm/tests/iota.ts
- identity_document/src/document/core_document.rs
- identity_iota_core/Cargo.toml
- identity_iota_core/README.md
- identity_iota_core/src/client/identity_client.rs
- identity_iota_core/src/client/iota_client.rs
- identity_iota_core/src/did/iota_did.rs
- identity_iota_core/src/document/iota_document.rs
- identity_iota_core/src/document/iota_document_metadata.rs
- identity_iota_core/src/error.rs
- identity_iota_core/src/lib.rs
- identity_iota_core/src/network/network_name.rs
- identity_iota_core/src/state_metadata/document.rs
- identity_iota_core/src/state_metadata/encoding.rs
- identity_iota_core/src/state_metadata/version.rs
Polish `identity_iota_core` by unifying method signatures across `IotaDocument` and `CoreDocument`, removing unused error variants, renaming `tag` to `tag_str` to be in line with `network_str` and making the `properties` field of `IotaDocumentMetadata` private so we can add more fields to the metadata struct without a breaking change in the future.
part of #1103
`cargo clippy`
> Polish `identity_iota_core`

- bindings/wasm/docs/api-reference.md
- bindings/wasm/src/storage/key_id_storage.rs
- bindings/wasm/src/storage/wasm_storage.rs
The storage classes referenced by the `@link` notations do not exist in the same file which causes broken links in the .md documentation.
> Fix broken links in Wasm Api-reference

- bindings/wasm/src/did/wasm_core_document.rs
- bindings/wasm/src/iota/iota_document.rs
- examples/0_basic/5_create_vc.rs
- examples/0_basic/6_create_vp.rs
- examples/0_basic/7_revoke_vc.rs
- examples/0_basic/8_stronghold.rs
- examples/1_advanced/6_domain_linkage.rs
- identity_storage/src/storage/jwk_document_ext.rs
- identity_storage/src/storage/tests/api.rs
- identity_storage/src/storage/tests/credential_jws.rs
- identity_storage/src/storage/tests/credential_validation.rs
- identity_storage/src/storage/tests/presentation_validation.rs
Bring `JwkDocumentExt` names in line with Wasm, since we agreed they are better.
n/a
n/a
> Bring `JwkDocumentExt` names in line with Wasm

- bindings/wasm/src/iota/iota_metadata_encoding.rs
- identity_core/src/common/one_or_set.rs
- identity_core/src/convert/base_encoding.rs
- identity_credential/src/domain_linkage/error.rs
- identity_credential/src/error.rs
- identity_credential/src/revocation/error.rs
- identity_credential/src/validator/vc_jwt_validation/error.rs
- identity_document/src/error.rs
- identity_iota_core/src/state_metadata/encoding.rs
- identity_iota_core/src/state_metadata/version.rs
- identity_jose/src/error.rs
- identity_jose/src/tests/es256.rs
- identity_storage/src/key_id_storage/method_digest.rs
- identity_storage/src/key_storage/ed25519.rs
- identity_verification/src/error.rs
Mark error enums and other enums to which it is applicable as non-exhaustive. This is in effort to be more future-proof and be able to add more variants in a non-breaking way.
Also feature-gate the `encode_jwk` function behind flags under which it is actually necessary.
n/a
`cargo clippy` for the non-exhaustive additions.
> Mark error enums as non-exhaustive

- examples/0_basic/6_create_vp.rs
- identity_credential/src/error.rs
- identity_credential/src/presentation/jwt_serialization.rs
- identity_credential/src/presentation/presentation.rs
- identity_credential/src/presentation/presentation_builder.rs
This change ensures that `verifiable_credential` in `Presentation` will serialize into a `[T]` instead of a `T`, which was previously the case when `verifiable_credential` would only hold one single credential.
This previous serialization is in line with how `credentialSubject` can be serialized: https://www.w3.org/TR/vc-data-model/#credential-subject, however this is not explicitly stated for `verifiableCredential`: https://www.w3.org/TR/vc-data-model/#presentations-0.
The following examples that are used in the specification seem to imply that 'single credentials' should be serialized as `[<credential>]`:
* https://www.w3.org/TR/vc-data-model/#example-a-simple-example-of-a-verifiable-presentation
* https://www.w3.org/TR/vc-data-model/#example-usage-of-the-termsofuse-property-by-a-holder …
> Change `verifiable_credential` to type `Vec<CRED>` in `Presentation`

- identity_credential/src/presentation/jwt_serialization.rs
Similar to https://github.com/iotaledger/identity.rs/pull/1235, holder wasn't checked for consistency in JWT presentation claims when decoding.
> Fix holder claim check in VP

- identity_credential/src/credential/jwt_serialization.rs
When JWT VC is validated, `check_consistency` will be called that checks if values are duplicated in the JWT claims and the VC itself in the `vc` claim. These values will be copied afterward when `Credential` is created after decoding. 
This works fine for all the claims except `iss`. It's not checked for consistency and it will be copied to the `properties` field in `Credential` instead of `issuer`. This PR fixes that and adds some tests. 
I expect similar issues in JWT VP. I will take a look and eventually open another PR.
> Fix issuer claim check in VC

- bindings/wasm/src/jose/jws_header.rs
- bindings/wasm/src/storage/signature_options.rs
- bindings/wasm/tests/storage.ts
- identity_jose/src/jws/header.rs
- identity_storage/src/storage/jwk_document_ext.rs
- identity_storage/src/storage/signature_options.rs
- identity_storage/src/storage/tests/credential_jws.rs
Now `JwsSignatureOptions` has the option to set arbitrary header parameters https://datatracker.ietf.org/doc/html/rfc7519#section-5
> Allow arbitrary JWS header parameters

- .github/actions/publish/publish-rust/action.yml
To solve dependency tree issue
See https://github.com/crate-ci/cargo-release/issues/605#issuecomment-1331359921
> Pin `cargo-release` version to `0.21.1`

- bindings/wasm/docs/api-reference.md
- bindings/wasm/src/common/imported_document_lock.rs
- bindings/wasm/src/credential/domain_linkage_validator.rs
- bindings/wasm/src/credential/jwt_credential_validation/jwt_credential_validator.rs
- bindings/wasm/src/credential/jwt_presentation_validation/jwt_presentation_validator.rs
- bindings/wasm/src/did/wasm_core_document.rs
- bindings/wasm/src/error.rs
- bindings/wasm/src/iota/identity_client_ext.rs
- bindings/wasm/src/iota/iota_document.rs
- bindings/wasm/tests/storage.ts
fixes #https://github.com/iotaledger/identity.rs/issues/1150
This PR change the methods requiring read/write to be fallible if the lock is acquired to prevent uncontrolled crashes, since blocking is not supported for `RwLock` in wasm.
> Fix wasm panic caused by a race condition in `IotaDocument` and `CoreDocument`

- README.md
- bindings/wasm/README.md
- examples/0_basic/0_create_did.rs
- identity_iota/README.md
Replace Wiki links with direct GitHub links to the private tangle setup. 
https://github.com/iotaledger/iota-wiki/pull/1281
> Replace private tangle links

- .github/actions/publish/publish-rust/action.yml
Split the command to better see potential issues and skip commits.
Tested locally
> Split cargo release command

- identity_credential/src/revocation/status_list_2021/credential.rs
Fixed a "bug" that allows for revoked credentials to become valid again.
Added a unit test.
> Credentials cannot be unrevoked with StatusList2021

- identity_credential/Cargo.toml
- identity_credential/src/revocation/revocation_bitmap_2022/bitmap.rs
Fixes an encoding error in `RevocationBitmap2022`.
Fixes issue #1291.
Our implementation of `RevocationBitmap2022` had a bug in the code that takes care of encoding the bitmap into a credential service URL. This bug caused a double base64 encoding for the binary list which this PR fixes.
All revocation bitmaps encoded as credential's services before this PR will still be properly decoded and any update on them will fix their encoding.
Added unit tests for both encoding and decoding functions.
> Fix RevocationBitmap2022 encoding bug

- bindings/wasm/docs/api-reference.md
- bindings/wasm/examples/src/1_advanced/6_sd_jwt.ts
- bindings/wasm/src/sd_jwt/encoder.rs
- bindings/wasm/tests/sd_jwt.ts
- examples/1_advanced/7_sd_jwt.rs
- examples/1_advanced/8_status_list_2021.rs
- examples/Cargo.toml
- identity_credential/Cargo.toml
- identity_storage/src/storage/tests/kb_jwt.rs
Update the dependency `sd-jwt-payload` to the version `0.2.0` and adapt its Wasm bindings.
> Update `sd-jwt-payload` dependency

- README.md
- identity_credential/Cargo.toml
The `roaring` crate feature gates some functions we use. Add the missing feature to fix compilation.
> Fix compilation error caused by the `roaring` crate

- identity_stronghold/src/stronghold_jwk_storage.rs
- identity_stronghold/src/tests/test_jwk_storage.rs
Retrieve public keys from `StrongholdStorage` by `KeyId`.
closes https://github.com/iotaledger/identity.rs/issues/1302
This function can't be added to the trait since that would be a breaking change and it doesn't seem necessary to force other implementations to add this function.
> Add `get_public_key` for `StrongholdStorage`

- Cargo.toml
- identity_core/Cargo.toml
- identity_credential/Cargo.toml
- identity_did/Cargo.toml
- identity_document/Cargo.toml
- identity_eddsa_verifier/Cargo.toml
- identity_iota/Cargo.toml
- identity_iota_core/Cargo.toml
- identity_jose/Cargo.toml
- identity_resolver/Cargo.toml
- identity_storage/Cargo.toml
- identity_stronghold/Cargo.toml
- identity_verification/Cargo.toml
Disable a clippy's `result_large_err` lints.
> Chore: allow large result err variants

- identity_verification/Cargo.toml
Inherit [repository](https://rust-digger.code-maven.com/about-repository) key for correctly labeling/pointing to the GitHub repo.
This makes location of the source code easier to see Crates.io. 🙂
This change only affects `identity_verification` crate. All other modules already correctly inherit repository.
*None*
*None*
> chore(cargo): inherit `repository` in identity_verification

- .github/workflows/grpc-publish-to-dockerhub.yml
- bindings/grpc/README.md
Fix dockerhub publish workflow and Readme links.
Successfully released to dockerhub using this workflow
> Fix dockerhub workflow

- bindings/wasm/src/verification/wasm_method_type.rs
- bindings/wasm/tests/core.ts
- bindings/wasm/tests/iota.ts
- identity_verification/src/verification_method/method.rs
- identity_verification/src/verification_method/method_type.rs
Support for JWK-based verification has long been added to the library but under a non-standardized type - i.e. `JsonWebKey`. This PR solves this issue by making the already implemented method spec-compliant by changing the method's type to `JsonWebKey2020` and deprecating the previous type.
Closes #1366
Ran linter and all tests.
> Support for specification-compliant verification method type `JsonWebKey2020`

- Cargo.toml
- bindings/wasm/Cargo.toml
- examples/Cargo.toml
- identity_credential/Cargo.toml
- identity_jose/Cargo.toml
- identity_storage/Cargo.toml
- identity_stronghold/Cargo.toml
The most recent version of [`bls12_381_plus`](https://crates.io/crates/bls12_381_plus/0.8.16) introduces adds changes to type conversion that may break builds due to conflicting implementations of `From` trait.
```raw
error[E0119]: conflicting implementations of trait `From<bls12_381_plus::scalar::Scalar>` for type `Issuer`
--> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/identity_credential-1.3.0/src/credential/issuer.rs:43:1
|
43 | / impl<T> From<T> for Issuer
44 | | where
45 | |   T: Into<Url>,
| |_______________^
|
= note: conflicting implementation in crate `bls12_381_plus`:
- impl From<bls12_381_plus::scalar::Scalar> for <bls12_381_plus::scalar::Scalar as ark_ff::fields::prime::PrimeField>::BigInt;
```
Pinning this dependency to the previous version hotfixes …
> Pin and bump `bls12_381_plus` dependency

- bindings/wasm/lib/key_id_storage.ts
- bindings/wasm/package-lock.json
- bindings/wasm/package.json
- identity_storage/src/key_id_storage/key_id_storage_error.rs
- identity_storage/src/storage/error.rs
Makes base64 encoding in `KeyIdMemStore`, `methodDigestToString` work for node and web targets. By using new dependency `base64-arraybuffer`.
Also adds smaller improvements for storage related errors.
Tested in browser and against local wasm tests.
> Make base64 encoding target independent in `KeyIdMemStore` in wasm bindings

- .github/workflows/build-and-test.yml
- bindings/wasm/cypress.config.ts
Reenable Firefox CDP to allow cypress control
- https://github.com/cypress-io/cypress/issues/29713
- https://github.com/cypress-io/cypress/issues/29714
CI passing
> Reenable legacy Firefox CDP support

- bindings/wasm/docs/api-reference.md
- bindings/wasm/examples/src/0_basic/2_resolve_did.ts
- bindings/wasm/src/did/did_jwk.rs
- bindings/wasm/src/did/mod.rs
- bindings/wasm/src/did/wasm_core_document.rs
- identity_did/Cargo.toml
- identity_did/src/did_jwk.rs
- identity_did/src/lib.rs
- identity_document/src/document/core_document.rs
- identity_iota_core/src/document/iota_document.rs
- identity_resolver/src/resolution/resolver.rs
- identity_verification/src/verification_method/method.rs
Add support for handling and resolving `did:jwk` DIDs.
WASM bindings included.
e2e and unit tests.
> Add support for `did:jwk` resolution

- identity_iota_core/packages/iota_identity/sources/asset.move
- identity_iota_core/packages/iota_identity/sources/identity.move
- identity_iota_core/packages/iota_identity/sources/proposals/borrow.move
- identity_iota_core/packages/iota_identity/sources/proposals/transfer.move
This PR introduces the emission of events for the following operations:
- `Identity` has a new proposal
- `Identity` has executed a proposal
- `Identity` has a proposal ready for execution
- `AuthenticatedAsset` transfer requested
- `AuthenticatedAsset` transfer concluded
> Emit Move events when performing operations on on-chain identities

- identity_iota_core/packages/iota_identity/sources/asset.move
- identity_iota_core/packages/iota_identity/sources/controller.move
- identity_iota_core/packages/iota_identity/sources/identity.move
- identity_iota_core/packages/iota_identity/sources/migration.move
- identity_iota_core/packages/iota_identity/sources/multicontroller.move
- identity_iota_core/packages/iota_identity/sources/permissions.move
- identity_iota_core/packages/iota_identity/sources/proposals/borrow.move
- identity_iota_core/packages/iota_identity/sources/proposals/config.move
- identity_iota_core/packages/iota_identity/sources/proposals/transfer.move
- identity_iota_core/packages/iota_identity/sources/proposals/value.move
- identity_iota_core/src/rebased/migration/identity.rs
- identity_iota_core/src/rebased/proposals/borrow.rs
- identity_iota_core/src/rebased/sui/move_calls/identity/borrow_asset.rs
- identity_iota_core/src/rebased/sui/move_calls/identity/config.rs
- identity_iota_core/src/rebased/sui/move_calls/identity/create.rs
- identity_iota_core/src/rebased/sui/move_calls/identity/deactivate.rs
- identity_iota_core/src/rebased/sui/move_calls/identity/proposal.rs
- identity_iota_core/src/rebased/sui/move_calls/identity/send_asset.rs
- identity_iota_core/src/rebased/sui/move_calls/identity/update.rs
- identity_iota_core/src/rebased/sui/move_calls/utils.rs
- identity_iota_core/tests/e2e/identity.rs
Introduces a new `store` token used for Identity's AC. When a controller is created the committee can choose whether to allow it to delegate its access through the `can_delegate` flag. If a controller can delegate its access it can mint `DelegationTokens` a blind token that can be freely traded and allows whatever entity it presents it to act in the stead of the controller that minted it.
`DelegationTokens` can be revoked and unrevoked by any controller.
> Onchain identity controller delegation

- identity_iota_core/src/rebased/migration/identity.rs
- identity_iota_core/src/rebased/proposals/borrow.rs
- identity_iota_core/src/rebased/proposals/mod.rs
- identity_iota_core/src/rebased/proposals/upgrade.rs
- identity_iota_core/src/rebased/sui/move_calls/identity/mod.rs
- identity_iota_core/tests/e2e/identity.rs
PR fixes clippy and fmt issues, that came up with parallel merges.
Checked against local formatters.
> Fix clippy and fmt issues

- identity_iota_core/packages/iota_identity/sources/identity.move
- identity_iota_core/packages/iota_identity/sources/migration.move
- identity_iota_core/src/rebased/iota/move_calls/identity/create.rs
Fix _Move_ lint warning that appeared when creating an Identity.
> Fix Move Identity creation warning

- examples/utils/utils.rs
- identity_iota_core/README.md
- identity_iota_core/src/rebased/client/full_client.rs
- identity_iota_core/src/rebased/utils.rs
- identity_iota_core/tests/e2e/common.rs
PR adds support to fund transactions with active address of local IOTA client.
This allows to run tests to be run against environments with a faucet with stricter rules than on localnet or against an environment without a faucet.
Running tests/examples with env variable IOTA_IDENTITY_FUND_WITH_ACTIVE_ADDRESS` set to `true` will use the local active address to send funds to new test/example accounts. For detail see `identity_iota_core/README.md`.
Another env variable to configure IOTA API endpoint has been added as well: `API_ENDPOINT`. Defaults to local test environment if unset.
#1469 
Tested against local network and devnet.
> Add support for "fauceting" test/example transaction via local active address

- identity_iota_core/src/rebased/client/full_client.rs
- Introduced a constant `MINIMUM_BALANCE` to define the minimum balance required for transactions.
- Updated `get_coin_for_transaction` method to iterate through paginated coin data, selecting the coin with the highest balance that meets the minimum requirement.
- Improved error handling to provide clearer messages when no suitable coins are found.
fixes issue #1470 
> Enhance coin retrieval logic in Iota client

- examples/utils/utils.rs
- identity_iota_core/Cargo.toml
- identity_iota_core/src/network/network_name.rs
- identity_iota_core/src/rebased/client/read_only.rs
- identity_iota_core/src/rebased/iota/mod.rs
- identity_iota_core/src/rebased/iota/well_known_networks.rs
- identity_iota_core/src/rebased/migration/identity.rs
- identity_iota_core/tests/e2e/client.rs
- identity_iota_core/tests/e2e/common.rs
Embed devnet's `IotaIdentity` package metadata into the library and adapt `NetworkName` to work with `ChainIdentifiers` instead of HRP.
> Add devnet package information

- identity_iota_core/src/rebased/client/read_only.rs
- identity_iota_core/src/rebased/iota/well_known_networks.rs
Fixes formatting issue from last PR.
Ran formatting steps locally to check.
> Fix formatting issue

- README.md
- identity_iota/README.md
> Fix README.md example code and instructions

- identity_iota_core/src/did/iota_did.rs
- identity_iota_core/src/rebased/client/read_only.rs
- identity_iota_core/src/rebased/iota/well_known_networks.rs
Tests were failing in CI because they weren't updated to support 8 characters long network ids. Fixed that. 
Also added network aliases for well known networks such as "devnet" and "testnet"
> Fix failing DID IOTA tests and add NetworkName alias for well known networks

- bindings/grpc/src/main.rs
- bindings/grpc/src/services/document.rs
- bindings/grpc/src/services/utils.rs
- fixes outdated `.create_identity` arguments
- replaces deprecated `get_public_key` calls with `get_public_key_with_type`
Checked build locally, with opening the PR against `main` tests will be fired with the correct CI steps.
> Fix gRPC binding build issues

- .github/workflows/audit.yml
- .github/workflows/build-and-test-grpc.yml
- .github/workflows/build-and-test.yml
- .github/workflows/clippy.yml
- .github/workflows/format.yml
Add support for CI in PRs that target `feat/...` branches, and removes CI triggers for `epic/...` branches (currently unused).
The audit workflow has been enabled for `support/...` targeting PRs as well. Summary of changes:
| workflow                  | change                       |
| ------------------------- | ---------------------------- |
| audit                     | + feat/** <br> + support/**  |
| build-and-test-grpc       | * epic/** -> feat/**         |
| build-and-test            | * epic/** -> feat/**         |
| clippy                    | * epic/** -> feat/**         |
| format                    | * epic/** -> feat/**         | 
Checked format, etc. locally, PR's CI should be triggered when openening this PR.
Add an …
> Add support for CI in PRs that target `feat/...` branches

- bindings/wasm/src/common/imported_document_lock.rs
- bindings/wasm/src/error.rs
- identity_credential/src/credential/jwt_serialization.rs
- identity_credential/src/domain_linkage/domain_linkage_validator.rs
- identity_credential/src/presentation/jwt_serialization.rs
- identity_credential/src/revocation/status_list_2021/entry.rs
- identity_credential/src/revocation/validity_timeframe_2024/revocation_timeframe_status.rs
- identity_did/Cargo.toml
- identity_did/src/did_url.rs
- identity_document/benches/deserialize_document.rs
- identity_document/src/document/core_document.rs
- identity_document/src/utils/did_url_query.rs
- identity_iota_core/src/document/iota_document.rs
- identity_iota_core/src/state_metadata/document.rs
- identity_jose/src/jws/decoder.rs
- identity_jose/src/jws/encoding/utils.rs
- identity_jose/src/jws/recipient.rs
Allow the use of %-encoded characters in DID URLs.
Closes #1492 
Updated unit tests.
> Support %-encoded characters in DID URL

- .github/workflows/shared-release.yml
- .github/workflows/upload-docs.yml
Same as https://github.com/iotaledger/iota-sdk/pull/1890.
- confirmed secret exists, will be fully tested during next release
> Use separate PAT as GitHub token

- identity_credential/Cargo.toml
Upgrade dependency `sd-jwt-payload` to latest version (v0.3.0).
> SD-JWT VC: use latest SD-JWT crate version

- bindings/wasm/identity_wasm/Cargo.toml
- bindings/wasm/identity_wasm/src/error.rs
- bindings/wasm/identity_wasm/src/resolver/mod.rs
This PR Introduces a new feature flag in crate identity_wasm to control the usage of the dependency identity_iota::resolver, which is currently not available for the wasm32 platform. Without the changes in this PR the identity_wasm crate is not build-able.
None
In folder `bindings/wasm/identity_wasm`:
`cargo build --lib --target wasm32-unknown-unknown`
> Repair identity-wasm build

- bindings/wasm/identity_wasm/Cargo.toml
- bindings/wasm/identity_wasm/src/error.rs
- bindings/wasm/identity_wasm/src/resolver/mod.rs
- bindings/wasm/iota_interaction_ts/lib/move_calls/asset/create.ts
- bindings/wasm/iota_interaction_ts/lib/move_calls/asset/delete.ts
- bindings/wasm/iota_interaction_ts/lib/move_calls/asset/transfer.ts
- bindings/wasm/iota_interaction_ts/lib/move_calls/asset/update.ts
- bindings/wasm/iota_interaction_ts/lib/move_calls/identity/borrow_asset.ts
- bindings/wasm/iota_interaction_ts/lib/move_calls/identity/config.ts
- bindings/wasm/iota_interaction_ts/lib/move_calls/identity/controller_execution.ts
- bindings/wasm/iota_interaction_ts/lib/move_calls/identity/create.ts
- bindings/wasm/iota_interaction_ts/lib/move_calls/identity/deactivate.ts
- bindings/wasm/iota_interaction_ts/lib/move_calls/identity/proposal.ts
- bindings/wasm/iota_interaction_ts/lib/move_calls/identity/send_asset.ts
- bindings/wasm/iota_interaction_ts/lib/move_calls/identity/update.ts
- bindings/wasm/iota_interaction_ts/lib/move_calls/identity/upgrade.ts
- bindings/wasm/iota_interaction_ts/lib/move_calls/migration.ts
- bindings/wasm/iota_interaction_ts/lib/move_calls/utils.ts
- bindings/wasm/iota_interaction_ts/package-lock.json
- bindings/wasm/iota_interaction_ts/package.json
- bindings/wasm/iota_interaction_ts/src/identity_move_calls.rs
- bindings/wasm/iota_interaction_ts/src/migration_move_calls.rs
- identity_iota_core/src/rebased/proposals/borrow.rs
- identity_iota_core/src/rebased/proposals/controller.rs
This PR provides changes needed to build the two wasm-bindgen crates/packages iota_interaction_ts and identity_wasm in the `feat/ts-move-calls` branch.
The latest state of `identity-rebased-alpha `has also been merged into this branch, so that there are few changes resulting from there.
> Some feat/ts-move-calls extensions

- .github/actions/rust/rust-setup/action.yml
- bindings/wasm/identity_wasm/Cargo.toml
- bindings/wasm/identity_wasm/examples/src/0_basic/0_create_did.ts
- bindings/wasm/identity_wasm/examples/src/0_basic/1_update_did.ts
- bindings/wasm/identity_wasm/examples/src/0_basic/2_resolve_did.ts
- bindings/wasm/identity_wasm/examples/src/0_basic/3_deactivate_did.ts
- bindings/wasm/identity_wasm/examples/src/1_advanced/4_custom_resolution.ts
- bindings/wasm/identity_wasm/examples/src/main.ts
- bindings/wasm/identity_wasm/lib/index.ts
- bindings/wasm/identity_wasm/lib/resolver.ts
- bindings/wasm/identity_wasm/src/error.rs
- bindings/wasm/identity_wasm/src/iota/iota_document.rs
- bindings/wasm/identity_wasm/src/resolver/mod.rs
- bindings/wasm/identity_wasm/src/resolver/resolver_config.rs
- bindings/wasm/identity_wasm/src/resolver/wasm_did_resolution_handler.rs
- bindings/wasm/identity_wasm/src/resolver/wasm_resolver.rs
- examples/1_advanced/10_zkp_revocation.rs
- examples/1_advanced/9_zkp.rs
- identity_iota/Cargo.toml
- identity_iota/src/lib.rs
- identity_iota_core/src/lib.rs
- identity_resolver/src/resolution/resolver.rs
Re-adds examples for did resolution via `Resolver` API:
- `0_basic/2_resolve_did.ts`
- `1_advanced/4_custom_resolution.ts`
`Resolver` API is re-added, but the `attach_iota_handler` and `attach_multiple_iota_handlers` parts are left out of the WASM build.
The Stardust implementation was already not using those two and was directly using a client with respective traits to resolve the DID. Updated implementation follows the same principle, but uses the new API for this.
> Re-add Resolver API for WASM builds

- bindings/wasm/iota_interaction_ts/lib/iota_client_helpers.ts
- bindings/wasm/iota_interaction_ts/src/bindings/wasm_iota_client.rs
- bindings/wasm/iota_interaction_ts/src/bindings/wasm_types.rs
- bindings/wasm/iota_interaction_ts/src/iota_client_ts_sdk.rs
- identity_iota_core/src/iota_interaction_rust/iota_client_rust_sdk.rs
- identity_iota_interaction/src/iota_client_trait.rs
- identity_iota_interaction/src/sdk_types/generated_types.rs
Adds a wait command to TS impl of `execute_transaction`, that ensures that an executed transaction is available.
> Add waiting for transaction block availability to TS variant of `execute_transaction`

- bindings/wasm/identity_wasm/src/iota/iota_document.rs
- bindings/wasm/identity_wasm/src/rebased/identity.rs
- bindings/wasm/iota_interaction_ts/lib/iota_client_helpers.ts
- bindings/wasm/iota_interaction_ts/src/bindings/wasm_iota_client.rs
- bindings/wasm/iota_interaction_ts/src/bindings/wasm_types.rs
- bindings/wasm/iota_interaction_ts/src/iota_client_ts_sdk.rs
- identity_iota_interaction/src/iota_client_trait.rs
- identity_iota_interaction/src/sdk_types/generated_types.rs
Fix consuming of document arguments when publishing document updates in WASM.
Documents are now cloned instead of passing it to follow up steps.
> Fix document consuming in WASM when publishing updates 

- .github/workflows/build-and-test.yml
Limit parallel test execution as it seems to cause flakiness with the faucet, especially in macos runners.  
CI passes
> Limit parallel test execution

- bindings/wasm/identity_wasm/lib/resolver.ts
- bindings/wasm/identity_wasm/src/common/timestamp.rs
- bindings/wasm/identity_wasm/src/credential/credential.rs
- bindings/wasm/identity_wasm/src/credential/jpt_credential_validator/jwp_verification_options.rs
- bindings/wasm/identity_wasm/src/credential/linked_domain_service.rs
- bindings/wasm/identity_wasm/src/credential/linked_verifiable_presentation_service.rs
- bindings/wasm/identity_wasm/src/credential/presentation/presentation.rs
- bindings/wasm/identity_wasm/src/credential/revocation/status_list_2021/credential.rs
- bindings/wasm/identity_wasm/src/did/jws_verification_options.rs
- bindings/wasm/identity_wasm/src/iota/iota_metadata_encoding.rs
- bindings/wasm/identity_wasm/src/jose/jwk.rs
- bindings/wasm/identity_wasm/src/rebased/wasm_identity_client.rs
- bindings/wasm/identity_wasm/src/rebased/wasm_identity_client_read_only.rs
- bindings/wasm/identity_wasm/src/storage/signature_options.rs
- bindings/wasm/typedoc.json
- examples/1_advanced/8_status_list_2021.rs
PR fixes issues errors that occurred when building typedoc docs.
`wasm-bindgen` version bump has fixed the generation of function documentation for the WASM build. The then valid documentation had unresolvable links, due to target not having documentation.
PR also enables `validation.notDocumented` flag in the typedoc options to have stricter rules regarding missing documentation, e.g. missing enum variant documentation (fixed in PR).
Build docs locally without errors or warnings.
> Fix typedoc issues

- bindings/wasm/identity_wasm/src/rebased/identity.rs
- bindings/wasm/identity_wasm/src/rebased/proposals/config_change.rs
- bindings/wasm/identity_wasm/src/rebased/proposals/deactivate_did.rs
- bindings/wasm/identity_wasm/src/rebased/proposals/send.rs
- bindings/wasm/identity_wasm/src/rebased/proposals/update_did.rs
- bindings/wasm/identity_wasm/src/rebased/wasm_identity_client.rs
- bindings/wasm/iota_interaction_ts/lib/iota_client_helpers.ts
- bindings/wasm/iota_interaction_ts/src/bindings/wasm_iota_client.rs
- bindings/wasm/iota_interaction_ts/src/bindings/wasm_types.rs
- bindings/wasm/iota_interaction_ts/src/iota_client_ts_sdk.rs
- bindings/wasm/iota_interaction_ts/src/lib.rs
- identity_iota_core/src/iota_interaction_rust/mod.rs
- identity_iota_core/src/rebased/proposals/borrow.rs
- identity_iota_core/src/rebased/proposals/config_change.rs
- identity_iota_core/src/rebased/proposals/controller.rs
- identity_iota_core/src/rebased/proposals/deactivate_did.rs
- identity_iota_core/src/rebased/proposals/mod.rs
- identity_iota_core/src/rebased/proposals/send.rs
- identity_iota_core/src/rebased/proposals/update_did_doc.rs
- identity_iota_core/src/rebased/proposals/upgrade.rs
This PR comprises the following renamings
bindings/wasm/iota_interaction_ts:
* Renamed `bindings::IotaTransactionBlockResponseAdapter` to `bindings::WasmIotaTransactionBlockResponseWrapper` (name is also used for the TS class in iota_client_helpers.ts)
identity_iota_core/src/iota_interaction_rust and
bindings/wasm/iota_interaction_ts:
* Renamed `AdapterNativeResponse` to `NativeTransactionBlockResponse`
* fixes issue #1514
* Replaces closed PR #1527
* Current E2E tests for non wasm32 targets run as expected
* Successful wasm32 and non wasm32 build for identity_iota_core:
wasm32 build: `cargo build --package identity_iota_core --lib --target wasm32-unknown-unknown --no-default-features --features iota-client --features revocation-bitmap`
* NPM build iota_interaction_ts:
In folder …
> Rename types in iota interaction ts and iota interaction rust

- bindings/wasm/src/resolver/wasm_resolver.rs
- identity_credential/src/credential/credential.rs
Make sure Credential's context gets serialized as a Set even when only the default context is present.
Closes issue #1550
Added a test.
> Credential's context is a set even when a single context value is present

- bindings/wasm/iota_interaction_ts/src/bindings/keytool_signer.rs
`TransactionSigner` requires an addictional method `iotaPublicKeyBytes` which was missing and is added with this PR.
> WASM: make KeytoolSigner extend the `TransactionSigner` interface

- .github/actions/iota-rebase-sandbox/setup/action.yml
- .github/workflows/build-and-test.yml
- bindings/grpc/tests/api/helpers.rs
- bindings/wasm/identity_wasm/package.json
- identity_iota_core/scripts/publish_identity_package.sh
- identity_iota_core/tests/e2e/common.rs
Adds some smaller improvements to output during tests, and fixes a smaller issue with build:
- `npm run build` now runs without errors on macOS again, as `fix_docs` now works as expected on macOS
- IOTA server logs from CI can now been downloaded (--> "Archive server logs" step)
- `identity_iota_core/scripts/publish_identity_package.sh` script now emits the response if it cannot be parsed, instead of the message that just says, that the JSON could not be parsed
- cli tools error logs in `identity_iota_core` and the GRPC bindings now all include `stderr` where a custom error is thrown
> Add smaller test and debug improvements

- .github/actions/rust/rust-setup/action.yml
- identity_core/Cargo.toml
Pin dependency `derange` depdendency of `time` and limit range, as `0.4.1` has impl for `usize: PartialOrd<_>`, that conflicts with `iota-sdk`s `core` impl, leading to errors in `iota-sdk` crate during build.
Tested build locally.
> Pin `derange` version to avoid conflicts in `iota-sdk`

- identity_core/Cargo.toml
Pin dependency `derange` depdendency of `time` and limit range, as `0.4.1` has impl for `usize: PartialOrd<_>`, that conflicts with `iota-sdk`s `core` impl, leading to errors in `iota-sdk` crate during build.
Tested build locally.
> Pin `derange` version to avoid conflicts in `iota-sdk` on alpha branch

- .github/actions/publish/publish-wasm/action.yml
- .github/actions/release/bump-versions/action.yml
- .github/actions/rust/rust-setup/action.yml
- .github/workflows/build-and-test.yml
- .github/workflows/clippy.yml
- .github/workflows/rust-automatic-release-and-publish.yml
- .github/workflows/rust-create-hotfix-pr.yml
- .github/workflows/rust-create-release-pr.yml
- .github/workflows/shared-build-wasm.yml
- .github/workflows/upload-docs.yml
- .github/workflows/wasm-automatic-release-and-publish.yml
- .github/workflows/wasm-create-hotfix-pr.yml
- .github/workflows/wasm-create-release-pr.yml
- .github/workflows/wasm-publish-to-npm.yml
- README.md
- bindings/wasm/Cargo.toml
- bindings/wasm/README.md
- bindings/wasm/package-lock.json
- bindings/wasm/package.json
- bindings/wasm/rust-toolchain.toml
- identity_credential/src/domain_linkage/domain_linkage_validator.rs
- identity_credential/src/domain_linkage/error.rs
- identity_iota/README.md
PR updates behavior for domain linkage validation when having multiple credentials issued by the same issuer:
- `validate_linkage` now allows multiple credentials by same issuer
- adds `validate_linkage_iter` to support custom validation setups here
Tested locally.
> Update domain linkage validation for multiple creds by same issuer

- bindings/wasm/src/credential/jpt_credential_validator/jpt_credential_validation_options.rs
- bindings/wasm/src/credential/jwt_credential_validation/jwt_credential_validator.rs
- bindings/wasm/src/credential/revocation/status_list_2021/credential.rs
- bindings/wasm/src/credential/revocation/validity_timeframe_2024/status.rs
- bindings/wasm/tests/storage.ts
- identity_core/Cargo.toml
- identity_core/src/common/ordered_set.rs
- identity_credential/src/presentation/jwt_serialization.rs
- identity_credential/src/revocation/status_list_2021/status_list.rs
- identity_credential/src/validator/jwt_credential_validation/error.rs
- identity_credential/src/validator/sd_jwt/error.rs
- identity_credential/src/validator/sd_jwt/validator.rs
- identity_jose/src/error.rs
- identity_jose/src/jws/encoding/utils.rs
- identity_storage/src/storage/tests/kb_jwt.rs
- identity_stronghold/src/storage/mod.rs
Reverts `deranged` pinning from #1622.
Also fixes clippy warning.
Checked build and clippy output locally.
> Revert deranged version pinning

- identity_core/src/common/ordered_set.rs
Latest version of proptest deprecated some methods, switch to the new ones.
> Don't use proptest deprecated methods

- identity_jose/src/jwk/key.rs
- identity_jose/src/jwk/key_params.rs
Adds `Jwk::into_public` and `Jwk::strip_private` to enable the same functionality of `Jwk::to_public` but without any cloning.
Closes #1680
> `Jwk::into_public` and `Jwk::strip_private`

- bindings/wasm/identity_wasm/src/rebased/wasm_identity_client.rs
- bindings/wasm/identity_wasm/src/rebased/wasm_identity_client_read_only.rs
`IdentityClient` can only be built though an async operation but the default constructor - inherited by Object - allows to create an instance, although an invalid one. This behavior is deceptive and hence we override the constructor with one that always fails with an error that mentions the correct way to instantiate the client.
Closes #1596
> WASM override default sync contructors

- examples/utils/utils.rs
- identity_credential/src/revocation/revocation_bitmap_2022/document_ext.rs
- identity_credential/src/validator/jpt_credential_validation/jpt_credential_validator_utils.rs
- identity_credential/src/validator/sd_jwt/validator.rs
- identity_iota_core/tests/e2e/common.rs
- identity_jose/src/jwk/conversion/ed25519.rs
Fixes some clippy issues, that came up in the latest CI runs.
Mostly "variables can be used directly in the `format!` string" ([clippy lint](https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args)) errors. And a single "swapping with a temporary value is inefficient" ([clippy lint](https://rust-lang.github.io/rust-clippy/master/index.html#swap_with_temporary)) error.
Re-checked clippy locally, using CI to check test runs.
> Fix clippy issues

- Cargo.toml
- bindings/grpc/Cargo.toml
- bindings/wasm/identity_wasm/Cargo.toml
- bindings/wasm/identity_wasm/package-lock.json
- bindings/wasm/identity_wasm/package.json
- examples/Cargo.toml
- identity_iota/Cargo.toml
- identity_iota_core/Cargo.toml
- identity_jose/Cargo.toml
- identity_storage/Cargo.toml
Following dependencies have been changed
* Pin iota tag = "v1.5.0"
* Pin all product-core cargo dependencies to tag = "v0.8.1"
* identity_wasm: Pin "@iota/iota-sdk": "^1.6.0" in package.json peerDependencies
Related to [[Task]: Upstream merge iota_interaction::sdk_types for IOTA v1.5.0-rc](https://github.com/iotaledger/product-core/issues/57)
> feat: pin iota v1.5.0 and product-core v0.8.1

- Cargo.toml
- bindings/grpc/Cargo.toml
- bindings/wasm/identity_wasm/Cargo.toml
- bindings/wasm/identity_wasm/package-lock.json
- bindings/wasm/identity_wasm/package.json
- examples/Cargo.toml
- identity_iota/Cargo.toml
- identity_iota_core/Cargo.toml
- identity_jose/Cargo.toml
- identity_storage/Cargo.toml
Following dependencies have been changed:
None
> feat: Update to iota v1.6.1 and product core v0.8.2

- Cargo.toml
- bindings/grpc/Cargo.toml
- bindings/wasm/identity_wasm/Cargo.toml
- examples/Cargo.toml
- identity_credential/src/revocation/status_list_2021/status_list.rs
- identity_iota/Cargo.toml
- identity_iota_core/Cargo.toml
- identity_iota_core/src/rebased/migration/multicontroller.rs
- identity_jose/Cargo.toml
- identity_storage/Cargo.toml
Following dependencies have been changed:
identity_wasm: @iota/iota-interaction-ts dependency stays with "^0.8.0"
None
> feat: Update to iota v1.7.0
