identity_core/Cargo.toml, identity_proof/Cargo.toml, identity_proof/src/signature/suites/jcsed25519signature2020.rs
* Works with WASM
* Will be used by crypto.rs crate
=> Use ed25519-zebra crate

docs/meeting-notes/2020-11-25.md
[Meeting notes](https://hackmd.io/@WZdHn6o0TmiYck3zlENRsw/Bkxag8K5D/edit)
=> (upcoming)-meeting/2020-11-25

docs/meeting-notes/2021-01-27.md
=> feat(meeting)/2021-01-27

bindings/wasm/Cargo.toml, bindings/wasm/README.md, bindings/wasm/package.json, identity-core/Cargo.toml, identity-credential/Cargo.toml, identity-did/Cargo.toml, identity-diff/Cargo.toml, identity-diff/derive/Cargo.toml, identity-iota/Cargo.toml, identity/Cargo.toml
* Update rust crate versions
* Update npm package name/readme/version
=> Pre-publish Tasks

.github/workflows/build-and-test.yml, bindings/wasm/package.json, bindings/wasm/webpack.config.js, bindings/wasm/yarn.lock
Updates JS dependencies for wasm bindings.
=> Update wasm deps

identity-account/Cargo.toml, identity-account/src/stronghold/result.rs, identity-account/src/stronghold/vault.rs, identity-account/src/utils/crypto.rs
Updates to the latest version of crypto.rs/stronghold.rs
=> Fix account-related dependencies

identity-account/src/lib.rs, identity-core/src/lib.rs, identity-credential/src/lib.rs, identity-did/src/lib.rs, identity-diff/src/lib.rs, identity-diff/src/option.rs, identity-iota/src/lib.rs
=> Fix clippy

bindings/wasm/src/lib.rs
=> Fix clippy 2

bindings/wasm/examples/node.js, bindings/wasm/src/credential/credential.rs
Remove `proof` property hack from wasm `VerifiableCredential`
Local examples
=> Fix wasm credential

bindings/wasm/Cargo.toml, bindings/wasm/src/wasm_document.rs, identity-iota/Cargo.toml, identity-iota/src/chain/diff.rs, identity-iota/src/chain/document.rs, identity-iota/src/chain/integration.rs, identity-iota/src/client/client.rs, identity-iota/src/did/doc/diff.rs, identity-iota/src/did/doc/iota_document.rs, identity-iota/src/did/doc/properties.rs, identity-iota/src/error.rs, identity-iota/src/tangle/message_ext.rs, identity-iota/src/tangle/message_index.rs, identity-iota/src/tangle/mod.rs, identity-iota/src/tangle/traits.rs
use iota-client instead of iota-core, because we will remove the latter probably soon
=> use iota_client

.github/workflows/build-and-test.yml, .github/workflows/clippy.yml, .github/workflows/coverage.yml, .github/workflows/format.yml
=> Use explicit paths for workflows

.github/workflows/build-and-test.yml, bindings/wasm/docs/api-reference.md, bindings/wasm/examples/node.js, bindings/wasm/examples/web.js, bindings/wasm/src/iota.rs, bindings/wasm/src/wasm_did.rs, bindings/wasm/src/wasm_document.rs, bindings/wasm/tests/wasm.rs, identity-account/src/stronghold/result.rs, identity-core/src/common/timestamp.rs, identity-core/src/crypto/key/collection.rs, identity-core/src/crypto/merkle_tree/merkle.rs, identity-core/src/crypto/proof/jcs_ed25519.rs, identity-iota/src/chain/document.rs, identity-iota/src/client/network.rs, identity-iota/src/did/doc/iota_document.rs
- Use `previousMessageId` setter
- Add getters for `DID` network URLs
- Support client usage without explicit config object
- Fix network node/explorer URLs
Wasm Examples
=> Fix wasm examples

examples/Cargo.toml, identity-account/Cargo.toml, identity-core/Cargo.toml, identity-core/src/common/url.rs, identity-iota/Cargo.toml, identity/Cargo.toml
Updating various depedencies
CI
=> Dependency updates

bindings/wasm/Cargo.toml, bindings/wasm/package.json, identity-account/Cargo.toml, identity-core/Cargo.toml, identity-credential/Cargo.toml, identity-did/Cargo.toml, identity-diff/Cargo.toml, identity-diff/derive/Cargo.toml, identity-iota/Cargo.toml, identity/Cargo.toml
=> Update crate versions

identity-core/src/common/url.rs, identity-iota/src/tangle/message_ext.rs
Read indexation payloads also from transaction payloads
Resolved a DID with a document inside of a transaction with the wasm example
=> Also read indexation payload from transaction payloads

bindings/wasm/README.md, bindings/wasm/examples/README.md
Describe the build process for the wasm bindings as that was previously missing. Also added a note in the `examples/README.md` to indicate that building is a pre-requisite for running the examples.
=> docs: Describe build process for wasm bindings

bindings/wasm/examples/resolution.js
The readDocument method has been renamed to resolve. This PR renames the method call in the example file resolution.js
calling the method resolution(config) in resolution.js runs without exceptions. 
=> replace deleted method readDocument(id) with resolve(id)

identity-account/src/stronghold/context.rs
Disable the custom logging of `riker` which cluttered the output of other logging outputs, without a way to disable it externally.
=> Disable riker logging

identity-core/src/crypto/signature/signature.rs
We received an error report:
```
`std::cell::Cell<bool>` cannot be shared between threads safely
...
= note: required because it appears within the type `identity::crypto::Signature`
```
which should be fixed by this PR. It essentially implements a type that mimics a thread-safe `Cell`.
=> Impl type that mimics a thread-safe `Cell`

documentation/docusaurus.config.js
- fix docusaurus base url 
- should fix bug where docusaurus site doesn't load properly
https://github.com/iotaledger/identity.rs/issues/301
=> fix docusaurus base URL

bindings/wasm/README.md, documentation/docusaurus.config.js, documentation/package.json, documentation/yarn.lock
* Upgraded docusaurus to improve mobile nav
* Fixed docs edit url
Changes were tested on a local docs site. 
=> Docs - Improve mobile nav and fix broken link

libjose/src/jwk/key.rs
Updates for latest version of clippy
CI
=> Fix libjose clippy lint

bindings/wasm/package-lock.json, bindings/wasm/package.json
Small version release to fix the `import.meta` bug (#338) and outdated wasm examples  (#342, #343).
Tests and examples pass locally and in CI.
=> Bump version to 0.3.5 for @iota/identity-wasm@dev

examples/README.md
Some of the low-level examples links were pointing to the wrong files.
Changed the file names to point to the correct example files. 
=> Fix low-level links

.github/workflows/deploy_docs_to_github_pages.yml, README.md, bindings/wasm/README.md, documentation/docusaurus.config.js
=> Update documentation links

bindings/wasm/package-lock.json, bindings/wasm/package.json
Small version release for the new history API (#347) and Wasm error improvements (#344).
Tests and examples pass locally and in CI.
=> Bump version to 0.3.6 for @iota/identity-wasm@dev

.github/workflows/build-and-test.yml, .github/workflows/examples.yml
added a second job for building and running the rust examples, added relevant caches and removed the the git ref input.
fixes issue #359 
ran through the jobs on github. forced failures locally.
=> Add Rust examples to GitHub Actions

bindings/wasm/README.md
* Removed comment about txm which causes a compilation error upon importing from the wiki
Changes were tested locally and deployed at https://lucas-tortora.github.io/iota-wiki/identity.rs/libraries/wasm/getting_started
=> Docs - fix imports in wiki

bindings/wasm/examples/src/private_tangle.js
Fixes failing example tests when nothing (undefined) is passed to the private-tangle example.
Wasm examples pass locally.
=> Fix Wasm private-tangle example

.github/workflows/build-and-test.yml
Remove caches from libjose to reduce global cache size. Rework remaining caches to use Corgo.lock hash. 
Ran action, all jobs pass.
=> use Cargo.lock for caches, remove libjose caches

bindings/wasm/package-lock.json, bindings/wasm/package.json
Small version release to expose `merge` functionality to wasm: #401
=> Bump to 0.3.10 for @iota/identity-wasm@dev

documentation/docs/getting-started/verifiable_credentials/overview.md
Initial prose introducing VCs in IOTA.
N/A
Built docs locally.
=> Initial content for VC Wiki Overview page

bindings/wasm/package-lock.json, bindings/wasm/package.json
=> bump wasm to `0.4.0`

bindings/wasm/Cargo.toml, identity-account/Cargo.toml, identity-comm/Cargo.toml, identity-core/Cargo.toml, identity-credential/Cargo.toml, identity-did/Cargo.toml, identity-diff/Cargo.toml, identity-diff/derive/Cargo.toml, identity-iota/Cargo.toml, identity/Cargo.toml
=> Bump crate versions to `0.4.0`

.github/workflows/shared-release.yml
Added missing condition, which makes the changelog generator run and fail for every merge ATM.
=> Add missing workflow condition

.github/workflows/shared-release.yml
Fix a copy-paste bug, that prevents releases form working correctly. 
=> Fix workflow release version

README.md, documentation/docs/workflow.md, documentation/sidebars.js
Added document describing the git and release workflow.
=> Add workflow document

.github/.github_changelog_generator, bindings/wasm/.github_changelog_generator
=> Disable issues for changelogs

.github/workflows/shared-create-hotfix-pr.yml
Add `release-branch` parameter to scope changelog to support branch
=> fix hotfix changelog

.github/actions/release/changelog-generator/action.yml
=> Fix script path for changelog descriptions

.github/actions/release/changelog-generator/action.yml
fix changelog path for release descriptions
=> Fix changelog path for release descriptions

.github/actions/release/changelog-generator/action.yml
Use our own image with the latest revision from https://github.com/github-changelog-generator/github-changelog-generator to get necessary bugfixes.
The change has already been on the support branch https://github.com/iotaledger/identity.rs/actions/runs/1683399961
=> Use own docker image for changelog generator

identity-iota/Cargo.toml
Same change as #579 as a hotfix for version 0.4.
See #579
=> Enable local proof-of-work fallback

.github/workflows/shared-release.yml
Turns out the condition was okay, but the set operation contained a faulty character that always evaluated to true.
Also fixed wrongly set variables on the way.
Ran test in a fresh repo.
=> Fix workflow variables

documentation/docs/workflow.md
add description for epic branch merges
=> Add description for epic branch merges

.github/workflows/shared-create-dev-release-pr.yml, .github/workflows/shared-create-main-release-pr.yml
This will ignore tags not on dev and main (e.g. support branches)
=> Ignore changelog tags not on dev or main

.github/workflows/shared-create-dev-release-pr.yml, .github/workflows/shared-create-main-release-pr.yml
This will ignore tags not on dev and main (e.g. support branches)
=> Ignore tags not on dev or main

bindings/wasm/package-lock.json, bindings/wasm/package.json
Updated node-fetch to address a security issue. For more information see: https://github.com/node-fetch/node-fetch/releases/tag/v2.6.7
Tested examples locally.
=> Use node-fetch >= 2.6.7

bindings/wasm/package-lock.json, bindings/wasm/package.json
Upgrade wasm-pack to the latest version. Should take care of the following security warnings:
- https://github.com/iotaledger/identity.rs/security/dependabot/bindings/wasm/package-lock.json/axios/open
- https://github.com/iotaledger/identity.rs/security/dependabot/bindings/wasm/package-lock.json/follow-redirects/open
fixes issue #608.
Ran the examples locally.
=> Use latest version of wasm-pack

bindings/wasm/package-lock.json, bindings/wasm/package.json
Upgrade cypress to the latest version. Takes care security warnings:
- https://github.com/iotaledger/identity.rs/security/dependabot/bindings/wasm/package-lock.json/json-schema/open
Ran the cypress examples locally.
=> Upgrade cypress

bindings/wasm/package-lock.json, bindings/wasm/package.json
Pin wasm-pack version due to a bug on windows.
https://github.com/rustwasm/wasm-pack/issues/1097
Ran examples locally.
=> Pin wasm-pack version to 0.10.1

bindings/wasm/package-lock.json, bindings/wasm/package.json
Upgrade mocha to the latest version. Takes care security warnings:
- https://github.com/iotaledger/identity.rs/security/dependabot/bindings/wasm/package-lock.json/nanoid/open
Ran the build and tests locally.
=> Update mocha to the latest version

bindings/wasm/package-lock.json, bindings/wasm/package.json
Upgrade webpack and related libraries to the latest version. Takes care security warnings:
- https://github.com/iotaledger/identity.rs/security/dependabot/bindings/wasm/package-lock.json/node-forge/open
Ran the build and tests examples locally.
=> Upgrade webpack and libs

.github/actions/release/changelog-generator/action.yml, .github/workflows/shared-release.yml
Cut other releases and surrounding text from GitHub release changelogs to make them as clean as possible.
fixes issue #558 
=> Cut other releases from release changelog

.github/workflows/build-and-test.yml
Fix path in `build-and-test` workflow to include `bindings/wasm/**`. 
=> Fix workflow path

.github/workflows/build-and-test.yml
This PR adds conditions to only run the jobs in `build-and-test` if the PR is not in "Draft" mode. The branch triggers should be unaffected by this.
In "Draft" mode the test where skipped in this PR. On setting "Ready for Review" the tests where executed.
=> Skip build and test on draft PRs

.github/workflows/stronghold-bindings.yml, bindings/stronghold-nodejs/Cargo.toml, bindings/stronghold-nodejs/LICENSE, bindings/stronghold-nodejs/README.md, bindings/stronghold-nodejs/package-lock.json, bindings/stronghold-nodejs/package.json
Add minimal Readme and our standard License to the Stronghold bindings.
Updated the package name in Cargo and NPM.
We can add extend on the Readme with examples later.
Verified the contents of the npm package with `npm pack && tar -xvzf *.tgz && rm -rf package *.tgz `.
The build results of this job should pass with the changes.
=> Add minimal Readme, License, and update package name of stronghold bindings

.github/actions/rust/sccache/setup-sccache/action.yml, .github/workflows/clippy.yml, .github/workflows/format.yml, bindings/stronghold-nodejs/build.rs
Add `clippy` and `fmt` checks for the stronghold-nodejs bindings to GitHub Actions.
Ran the commands locally, the CI for this PR should pass.
=> Add Stronghold bindings clippy, fmt checks in CI

identity-did/src/diff/method_data.rs, identity-did/src/verification/method_data.rs
Remove `MethodData::publicKeyJwk`.
fixes issue #713
=> Remove `publicKeyJwk`

bindings/stronghold-nodejs/package-lock.json, bindings/stronghold-nodejs/package.json
Reverts changes necessary for the manual release of the stronghold nodejs bindings. 
=> Revert release changes

bindings/stronghold-nodejs/js/stronghold.ts, bindings/wasm/docs/api-reference.md
=> Fix stronghold.ts key types

bindings/wasm/README.md
Use builder in Readme examples.
=> Update Wasm Readme examples

.github/releases/v0.5.0.md, .github/releases/wasm-v0.5.0.md
=> Fix release description formatting

bindings/wasm/src/account/storage/traits.rs
Update the `Storage` typescript interface's documentation to match the Rust version.
n/a
=> Update `WasmStorage` Typescript interface docs

bindings/wasm/src/account/storage/traits.rs
`support/wasm-v0.5` is a protected branch, this just merges in the latest commit to it.
=> Merge dev to support branch

.github/workflows/wasm-create-hotfix-pr.yml
Fixes the hard-coded path needed for the temporary fix for the "Create Wasm Hotfix PR" GitHub Action workflow from #801.
NOTE: once again this only affect the `support/wasm-v0.5` hotfix branch, not `dev`.
See #800
We test in production (it's just really difficult to test these intertwined workflows locally, even with ACT).
=> Fix Wasm Hotfix PR workflow path

documentation/docs/contribute.md, documentation/docs/glossary.md, documentation/docs/workflow.md
TW style guide and diataxis review applied to Identity documentation. Sections reviewed include:
- Glossary
- Contribute
- and Workflow
=> Style Guide and Diataxis Review: Identity IV

documentation/docs/verifiable_credentials/verifiable_presentations.mdx
Updates and expands the [Verifiable Presentations](https://wiki.iota.org/identity.rs/verifiable_credentials/verifiable_presentations) wiki article for the 0.5.0 release.
Closes #792.
Ran the wiki-cli tool locally:
- `cd documentation`
- `npm run setup`
- `npm run start`
Navigate to http://localhost:3000/identity.rs/verifiable_credentials/verifiable_presentations
=> Update Verifiable Presentations wiki article

.github/workflows/build-and-test.yml
Run build-and-test workflow on branches targeting support branches.
=> Run build-and-test for support branches

documentation/docs/decentralized_identifiers/update.mdx, identity/README.md
Use links pointing to the `support/v0.5` branch
=> Use links pointing to support branch

documentation/docs/libraries/wasm/api_reference.md, documentation/docs/libraries/wasm/getting_started.md
Hi, it's me again 😅 
There is another problem with using the @site alias as it resolves to the directory of the room `docusaurus.config` which in our case is in the wiki. I could create a custom alias (like I did here: https://github.com/Dr-Electron/identity.rs/commit/7c60dd423b3accef59a35d26514629931ba69441) which would work, but later on with versioning I would need a unique custom alias for every version. Which isn't really maintainable 😅.
So I guess we just go for relative links. Maybe I can come up with something more clever somewhere down the road but for now it shouldn't really be a problem 😅 
Tested this locally and tried to add it to the wiki build.
=> Use relative links

documentation/docusaurus.config.js
Changed the repository part from `identity` to `identity.rs`.
Tested locally.
=> Fix edit URL

documentation/README.md, documentation/docusaurus.config.js, documentation/yarn.lock
Added the needed version info. 
Checklist:
https://github.com/iota-community/iota-wiki/issues/555
Tested locally and on our staging website https://versioning.iota-community.org/identity.rs/introduction
=> Add documentation version info for Develop

documentation/README.md, documentation/docusaurus.config.js, documentation/yarn.lock
Added the needed version info. 
Checklist:
https://github.com/iota-community/iota-wiki/issues/555
Tested locally and on our staging website https://versioning.iota-community.org/identity.rs/introduction
=> Add documentation version info for 0.5.0

.github/actions/publish/publish-rust/action.yml, .github/workflows/rust-publish-to-crates.yml, .github/workflows/rust-release-to-crates.yml
Add manual Rust release job for publishing to crates.io.
Closes #869.
Tested the command locally, job can only be tested on github after we merge it to `dev`.
=> Add Rust publish workflow

.github/actions/publish/publish-rust/action.yml
Fix crates.io workflow path to run in root of project.
Ran this version of the workflow through actions.
=> Fix crates.io workflow path

.github/actions/publish/publish-rust/action.yml
Fix crates.io workflow dry-run condition.
Ran this version of the workflow through actions.
=> Fix crates.io workflow dry-run condition

bindings/wasm/docs/api-reference.md, bindings/wasm/src/did/wasm_document.rs, examples/low-level-api/resolve_history.rs, identity-account/src/updates/update.rs, identity-iota-core/src/document/iota_document.rs, identity-iota/src/chain/diff_chain.rs
Small change to make `remove_service` consistent with `insert_service`.
Unit tests pass locally.
=> Change `remove_service` to return boolean

.github/actions/release/bump-versions/action.yml
Fixes a bug with the automatic version bump of the Identity Wasm `Cargo.toml`. 
Ran the command locally.
=> Fix Wasm version bump

README.md
Update the roadmap table in the Readme to reflect the current state of the framework.
Inspected the Markdown preview.
=> Update Readme roadmap

documentation/docs/concepts/decentralized_identifiers/private_tangle.mdx
Fix title of DID on private Tangle
=> Fix title of DID on private Tangle

documentation/docs/concepts/decentralized_identifiers/private_tangle.mdx
=> Fix title of DID on private Tangle (#885)

identity-iota-core/Cargo.toml, identity-iota-core/README.md, identity-iota-core/src/did/mod.rs, identity-iota-core/src/diff/diff_iota_document.rs, identity-iota-core/src/diff/diff_iota_document_metadata.rs, identity-iota-core/src/diff/diff_message.rs, identity-iota-core/src/document/iota_document.rs, identity-iota-core/src/document/mod.rs, identity-iota-core/src/lib.rs, identity-iota-core/src/tangle/mod.rs, identity-iota-core/src/tangle/network.rs, identity/src/lib.rs
Brief description for the `identity-iota-core` README.md.
- Fix broken intra-doc links.
- Add brief module descriptions.
- Make error module private: Error, Result already exported directly.
Addresses task in #133.
`cargo doc --no-deps --open` reports no errors or warnings.
=> Update `identity-iota-core` description

identity-iota/Cargo.toml, identity-iota/README.md, identity-iota/src/chain/diff_chain.rs, identity-iota/src/chain/document_chain.rs, identity-iota/src/chain/mod.rs, identity-iota/src/credential/mod.rs, identity-iota/src/credential/validation_options.rs, identity-iota/src/document/mod.rs, identity-iota/src/lib.rs, identity-iota/src/tangle/explorer.rs, identity-iota/src/tangle/mod.rs, identity-iota/src/tangle/resolver.rs, identity/src/lib.rs
Brief description for the `identity-iota` README.md.
- Fix broken intra-doc links.
- Add brief module descriptions.
- Make error module private: Error, Result already exported directly.
Addresses task of #133
`cargo doc --no-deps --open` reports no warnings or errors.
=> Update `identity-iota` description

README.md
Link to the new project board from the Readme.
=> Change Readme link to new project board

identity-diff/Cargo.toml, identity-diff/README.md, identity-diff/derive/Cargo.toml, identity-diff/derive/README.md, identity-diff/derive/src/lib.rs, identity-diff/src/lib.rs
Link crate README.md descriptions.
Addresses task in #133.
`cargo doc` reports no warnings or errors.
=> Update `identity-diff`, `identity-diff-derive` descriptions

.github/releases/v0.6.0.md, .github/releases/wasm-v0.6.0.md
Add release blurb for 0.6.0 for Wasm and Rust.
=> Add release blurb for 0.6.0

.github/actions/publish/publish-rust/action.yml
Enable Rust release in the `Rust publish to crates.io` action.
=> Enable Rust publish

.github/actions/publish/publish-rust/action.yml, .github/workflows/rust-publish-to-crates.yml
=> Fix Rust crates publish

.github/actions/publish/publish-rust/action.yml
Remove check temporarily.
n/a
n/a
=> Force Rust publish

documentation/package.json, documentation/yarn.lock
=> Update package name

documentation/docusaurus.config.js
Sorry, totally forgot to fix the version path in my last PR. Otherwise routes will collide
=> Add version path

documentation/docs/introduction.md
Fix link in documentation introduction page. 
=> Remove localhost from link (#914)

identity_account_storage/Cargo.toml, identity_account_storage/src/storage/stronghold.rs
Merging #928 to update stronghold to 0.6.4 to fix an incompatibility in a transitive dependency.
=> Update stronghold to 0.6.4

.github/releases/v0.7.0-alpha.1.md, .github/releases/wasm-v0.7.0-alpha.1.md
Add release blurb for the 0.7.0-alpha release.
Once we settle on the text, I will copy it over to Wasm.
=> Add 0.7.0-alpha release blurb

bindings/wasm/README.md, bindings/wasm/examples/src/ex0_create_did.ts, bindings/wasm/lib/tsconfig.json, bindings/wasm/lib/tsconfig.web.json, bindings/wasm/package-lock.json, bindings/wasm/package.json, documentation/docs/concepts/decentralized_identifiers/resolve.mdx
This PR replaces the iota-client-wasm bindings with a version published under the @iota namespace.
This CI passes.
=> Use iota scoped package

.github/actions/publish/publish-rust/action.yml, Cargo.toml, examples_legacy/Cargo.toml, identity_account/Cargo.toml, identity_account_storage/Cargo.toml, identity_iota_client_legacy/Cargo.toml, identity_iota_core_legacy/Cargo.toml
Reorganize workspace to exclude legacy crates from release.
=> reorg workspace members, error on mismatched dependencies

CHANGELOG.md, bindings/stronghold-nodejs/Cargo.toml, bindings/wasm/Cargo.toml, examples/Cargo.toml, examples_legacy/Cargo.toml, identity_account/Cargo.toml, identity_account_storage/Cargo.toml, identity_agent/Cargo.toml, identity_core/Cargo.toml, identity_credential/Cargo.toml, identity_did/Cargo.toml, identity_diff/Cargo.toml, identity_diff/derive/Cargo.toml, identity_iota/Cargo.toml, identity_iota_client_legacy/Cargo.toml, identity_iota_core/Cargo.toml, identity_iota_core_legacy/Cargo.toml, identity_resolver/Cargo.toml
This reverts commit bea72400b578fc6813b9a0109c9e844e2f53898f.
Revert version bump to rerun `0.7.0-alpha.1` release.
=> Revert "changelog and versions (#1015)"

.github/actions/release/bump-versions/action.yml
Bump agent versions during release to be consistent with the other crates.
n/a
None
=> Bump agent versions during release

bindings/stronghold-nodejs/Cargo.lock, identity_account_storage/Cargo.toml, identity_iota_core_legacy/Cargo.toml
Fix stronghold-nodejs build by bumping the versions of legacy crates so they match the now updated ones.
n/a
`cargo check`
=> Fix stronghold-nodejs build

documentation/docs/concepts/decentralized_identifiers/create.mdx
Add a small section about private network ("private Tangle") usage in the wiki.
fixes #1006
None.
=> Add private network wiki info

.github/workflows/build-and-test.yml, .github/workflows/clippy.yml, .github/workflows/coverage.yml, .github/workflows/format.yml, .github/workflows/rust-automatic-release-and-publish.yml, .github/workflows/rust-create-hotfix-pr.yml, .github/workflows/rust-create-release-pr.yml, .github/workflows/shared-create-dev-release-pr.yml, .github/workflows/shared-create-main-release-pr.yml, .github/workflows/test-docs-build.yml, .github/workflows/wasm-automatic-release-and-publish.yml, .github/workflows/wasm-create-hotfix-pr.yml, .github/workflows/wasm-create-release-pr.yml, README.md, bindings/stronghold-nodejs/README.md, bindings/wasm/README.md, documentation/docs/concepts/decentralized_identifiers/create.mdx, documentation/docs/concepts/decentralized_identifiers/delete.mdx, documentation/docs/concepts/decentralized_identifiers/resolve.mdx, documentation/docs/concepts/decentralized_identifiers/update.mdx, documentation/docs/concepts/verifiable_credentials/create.mdx, documentation/docs/concepts/verifiable_credentials/revocation.mdx, documentation/docs/concepts/verifiable_credentials/verifiable_presentations.mdx, documentation/docs/getting_started/create_and_publish.mdx, documentation/docs/getting_started/install.mdx, documentation/docs/libraries/rust/getting_started.md, documentation/docs/tutorials/validate_university_degree.mdx, identity_iota/README.md, identity_iota/src/lib.rs
Replace references to the `dev` branch with `main`.
=> Update main references

bindings/wasm/src/resolver/wasm_resolver.rs, documentation/docs/concepts/decentralized_identifiers/resolve.mdx
Updates the `Resolver` Wiki with a multi-method resolution example as well as updating the documentation to accurately reflect the current state of the `Resolver`. 
In part 2 of the Resolution wiki article update we will describe how to use the `Resolver` to handle verifiable presentations and possibly also how to resolve IOTA DIDs across different networks. These are things we cannot do now because the former (ideally) needs a new storage interface and the latter requires the `Resolver` to be extended with a method to attach a `ClientMap`.  
Opened the documentation locally in my browser and it looks decent. 
=> Update Resolution wiki article Part 1

.github/workflows/shared-create-dev-release-pr.yml
Disable changelog generator since it seems to can not deal with main being the default branch.
=> Disable changelog generator for dev releases

.github/actions/release/bump-versions/action.yml
Disable legacy version bump, because it currently fails.
=> Disable legacy version bump

CHANGELOG.md, README.md, bindings/wasm/CHANGELOG.md, bindings/wasm/README.md, documentation/docs/getting_started/install.mdx, documentation/docs/libraries/rust/getting_started.md, identity_iota/README.md
Update references to match latest release.
=> Update readme, wiki and changelogs

documentation/docs/getting_started/create_and_publish.mdx
Update `create_and_publish` wiki page for the UTXO method.
=> Update `create_and_publish` wiki page

.github/actions/publish/publish-rust/action.yml
We need to pin the `cargo-release` version, since the latest release introduced breaking changes that need more investigation to integrate.
Tracked in #1065 
Can only be tested in CI.
=> Pin cargo-release version

bindings/wasm/examples/src/0_basic/0_create_did.ts, bindings/wasm/examples/src/0_basic/1_update_did.ts, bindings/wasm/examples/src/0_basic/2_resolve_did.ts, bindings/wasm/examples/src/0_basic/3_deactivate_did.ts, bindings/wasm/examples/src/0_basic/4_delete_did.ts, bindings/wasm/examples/src/0_basic/5_create_vc.ts, bindings/wasm/examples/src/0_basic/6_create_vp.ts, bindings/wasm/examples/src/0_basic/7_revoke_vc.ts, bindings/wasm/examples/src/1_advanced/0_did_controls_did.ts, bindings/wasm/examples/src/1_advanced/1_did_issues_nft.ts, bindings/wasm/examples/src/1_advanced/2_nft_owns_did.ts, bindings/wasm/examples/src/1_advanced/3_did_issues_tokens.ts, bindings/wasm/examples/src/1_advanced/4_key_exchange.ts, bindings/wasm/examples/src/1_advanced/5_custom_resolution.ts, bindings/wasm/package-lock.json, bindings/wasm/package.json
Fix linting issue by running `dprint fmt`, which caused CI to fail on `main`. 
`dprint` is now added to the dev dependencies and a script is added to `package.json`.
I'm not sure why CI didn't catch this issue which was caused by this [PR](https://github.com/iotaledger/identity.rs/pull/1081).
=> Fix TS Linting

CHANGELOG.md
Add Rust changelog for v0.7.0-alpha.4.
=> Add Rust changelog for v0.7.0-alpha.4

identity_agent/Cargo.toml
Downgrade `identity_iota_core` dev dependency of the `identity_agent` to path only to fix a potential problem during release.
`cargo check`
=> Downgrade `identity_iota_core` dev dependency to path only

identity_agent/Cargo.toml
Do not publish the identity_agent for now, while it is not in a very useful state.
n/a
None.
=> Do not publish agent for now

bindings/wasm/package-lock.json, bindings/wasm/package.json
Use the latest version of `@iota/iots.js`. With this change we will accept any `2.0.0-rc` same as we did for `1.9.0-stardust` before.
Test in CI pass.
=> Update iota.js peer dependency

Cargo.toml, identity_agent/Cargo.toml, identity_core/Cargo.toml, identity_credential/Cargo.toml, identity_did/Cargo.toml, identity_diff/Cargo.toml, identity_document/Cargo.toml, identity_verification/Cargo.toml
Hoist `serde_json` into workspace `Cargo.toml` to deduplicate the crate version specification.
n/a
Everything still compiles.
=> Hoist `serde_json` into workspace `Cargo.toml`

bindings/wasm/docs/api-reference.md, bindings/wasm/src/error.rs, examples/1_advanced/5_alias_output_history.rs, identity_iota_core/src/client/iota_client.rs
Adapt the changes of the latest `iota-client` release.
=> Adapt changes of `iota-client`

bindings/wasm/Cargo.toml, identity_diff/README.md, identity_iota_core/Cargo.toml
This fixes broken nightly doc builds by updating `iota-types`. 
`cargo doc +nightly --all-features` succeeds locally. 
=> Update `iota-types` 

Cargo.toml
Remove agent from workspace for 0.7.0-alpha.5 release
n/a
n/a
=> Remove agent from workspace for 0.7.0-alpha.5 release

.github/actions/rust/rust-setup/action.yml, .github/workflows/shared-build-wasm.yml, bindings/wasm/rust-toolchain.toml, rust-toolchain.toml
Use toolchain files for the main library and the Wasm bindings. Manually install rust toolchain and components through rustup to respect toolchain files. 
=> Adopt toolchain file and replace toolchain action with manual commands

.github/workflows/format.yml, bindings/wasm/build/replace_paths.js, bindings/wasm/cypress.config.ts, bindings/wasm/cypress/e2e/0_basic/0_create_did.cy.js, bindings/wasm/cypress/e2e/0_basic/1_update_did.cy.js, bindings/wasm/cypress/e2e/0_basic/2_resolve_did.cy.js, bindings/wasm/cypress/e2e/0_basic/3_deactivate_did.cy.js, bindings/wasm/cypress/e2e/0_basic/4_delete_did.cy.js, bindings/wasm/cypress/e2e/0_basic/5_create_vc.cy.js, bindings/wasm/cypress/e2e/0_basic/6_create_vp.cy.js, bindings/wasm/cypress/e2e/0_basic/7_revoke_vc.cy.js, bindings/wasm/cypress/e2e/1_advanced/0_did_controls_did.cy.js, bindings/wasm/cypress/e2e/1_advanced/1_did_issues_nft.cy.js, bindings/wasm/cypress/e2e/1_advanced/2_nft_owns_did.cy.js, bindings/wasm/cypress/e2e/1_advanced/3_did_issues_tokens.cy.js, bindings/wasm/cypress/e2e/1_advanced/4_key_exchange.cy.js, bindings/wasm/cypress/e2e/1_advanced/5_custom_resolution.cy.js, bindings/wasm/cypress/e2e/1_advanced/6_domain_linkage.cy.js, bindings/wasm/cypress/support/setup.js, bindings/wasm/examples/src/util.ts, dprint.json
Fix dprint format issues. Run dprint on PRs touching `.js`, `.ts` or `.json` files.
CI passes.
=> Also run dprint action for `js`, `ts` and `json`

identity_did/Cargo.toml, identity_document/Cargo.toml, identity_iota_client_legacy/Cargo.toml
Pin `form_urlencoded` crate to temporarily avoid breaking changes.
Related to https://github.com/iotaledger/identity.rs/pull/1135
=> pin `form_urlencoded`

.github/workflows/build-and-test.yml, .github/workflows/clippy.yml, .github/workflows/format.yml, .github/workflows/test-docs-build.yml
Update workflow pattern to include PRs targeting support branches
=> Update workflow pattern

.github/workflows/build-and-test.yml, .github/workflows/wasm-publish-to-npm.yml
=> Fix workflow paths

.github/actions/publish/publish-wasm/action.yml, .github/workflows/build-and-test.yml, .github/workflows/shared-build-and-test-stronghold-nodejs.yml, bindings/stronghold-nodejs/package.json
Fix string quoting in bash preventing dry-run to ever be disabled.
=> Fix npm dry-run condition

bindings/wasm/lib/index.ts, bindings/wasm/lib/jwk_storage.ts, bindings/wasm/lib/key_id_storage.ts, bindings/wasm/tests/jwk_storage.ts, bindings/wasm/tests/key_id_storage.ts, bindings/wasm/tests/storage.ts
=> Move jwk_storage and key_id_storage to WASM lib

bindings/wasm/README.md
Fixed links to Wasm account and advanced examples.
fixes  https://github.com/iotaledger/guild-devx/issues/114
Wiki was built locally.
=> Docs - Support v0.6 - Fix links to examples

documentation/docs/concepts/domain_linkage/domain_linkage.mdx
Add an info box to make users aware that Domain Linkage is feature-gated in Rust.
=> Add domain linkage feature notice

identity_did/src/error.rs, identity_verification/src/error.rs, identity_verification/src/verification_method/builder.rs, identity_verification/src/verification_method/material.rs, identity_verification/src/verification_method/method.rs, identity_verification/src/verification_method/method_type.rs
Polish `identity_did` & `identity_verification` by removing unused types and resolving outstanding TODOs.
part of #1103.
`cargo check && cargo test`
=> Polish `identity_did` & `identity_verification`

.github/workflows/shared-build-wasm.yml, .github/workflows/wasm-publish-to-npm.yml
Use passed branch to build Wasm.
Impossible to test locally, first test will be successful `build-and-test` run after merge and then a release form a non-main branch.  
=> Respect passed branch for Wasm build

Cargo.toml
Readd examples to workspace which was exlucded for the release workflow.
=> Readd examples in 0.6

.github/actions/publish/publish-rust/action.yml
fixes https://github.com/iotaledger/identity.rs/pull/1249/
=> Pin `cargo-release` version to `0.20.1`

README.md, identity_iota/README.md
Change crate version in Readme so it can resolved. 
- [] I have commented my code, particularly in hard-to-understand areas
=> Fix version in Readme

.cargo/audit.toml, .github/workflows/audit.yml
Temporarily ignore  RUSTSEC-2023-0065
=> Update audit ignore

identity_did/src/did_url.rs, identity_stronghold/src/stronghold_jwk_storage.rs, identity_stronghold/src/stronghold_key_id.rs
fixes https://github.com/iotaledger/identity.rs/actions/runs/6457371214/job/17528715005?pr=1255
=> Fix clippy warnings

.github/actions/publish/publish-rust/action.yml
Update cargo release to potentially fix an issue with path dev-dependencies during release
relates to #1065 
Will need to be tested in CI
Note: This will likely break with our current crate structure so we need to reorganize it. Let's hope dry-run catches it 🤞 
=> Update cargo release

.github/actions/publish/publish-rust/action.yml
Remove legacy parameters.
Ran in CI.
=> Fix cargo release invocation

.github/actions/release/bump-versions/action.yml, bindings/wasm/Cargo.toml
Fix issue with updating local crates referenced by path and version.
Ran through version bump locally.
=> Remove local versions from Wasm crate

identity_credential/Cargo.toml
Remove dev dependency version from `identity_credential` which interferes with releases.
Successful alpha release from this branch.
=> Remove dev dependency version

.github/actions/iota-sandbox/setup/action.yml, .github/actions/iota-sandbox/tear-down/action.yml, .github/workflows/build-and-test.yml, README.md, bindings/wasm/README.md, bindings/wasm/examples/src/util.ts, examples/0_basic/0_create_did.rs, examples/0_basic/8_stronghold.rs, examples/utils/utils.rs, identity_iota/README.md
Use IOTA sandbox for examples and CI.
fixes issue #1289 
CI passes
=> Adapt to IOTA sandbox

identity_credential/Cargo.toml, identity_verification/src/verification_method/material.rs, identity_verification/src/verification_method/method_type.rs
I have added a new `MethodData` and `MethodType` to respectively support [`BlockchainAccountId`](https://www.w3.org/TR/did-spec-registries/#blockchainaccountid) and [`EcdsaSecp256k1RecoverySignature2020`](https://www.w3.org/TR/did-spec-registries/#ecdsasecp256k1recoverymethod2020).
**Minor fix**: added `features = ["serde"]` to fix missing de/seralization in `bitmap.rs` for the `roaring` crate.
Run the `0_create_did` example with the following code. 
```Rust
let id = document.id().to_url().join("#ethAddress")?;
// Add eth addr as verification method: https://www.w3.org/TR/did-spec-registries/#blockchainaccountid 
let method = MethodBuilder::default()
.id( id ) …
```
=> Add new Verification method type

examples/Cargo.toml
https://github.com/iotaledger/identity.rs/issues/1316
=> Fix example crate compilation with `--no-default-features` 

.github/workflows/build-and-test.yml
Also run `cargo check` for examples
Run in CI
=> Include examples in cargo check

bindings/wasm/src/sd_jwt/wasm_sd_jwt.rs, examples/Cargo.toml, identity_credential/Cargo.toml
Use latest release of `sd-jwt-payload`. 
Closes #1327
=> use latest release of sd-jwt-payload

README.md, identity_iota/README.md
=> Fix readme links

.github/actions/iota-sandbox/setup/action.yml
Add faucet to CI's sandbox environment
=> Chore: add inx-faucet profile

.github/actions/iota-sandbox/tear-down/action.yml
Update `docker compose down` command to use latest API
=> Fix sandbox teardown

README.md, identity_iota/README.md
=> Fix crate version in readme

examples/1_advanced/4_identity_history.rs, identity_iota_core/src/did/iota_did.rs, identity_iota_core/src/document/iota_document.rs, identity_iota_core/src/rebased/migration/identity.rs
PR replaces occurrence of things like "alias output", "alias id", etc. with references to the identity or its object id.
=> Update wording to "identity"

identity_iota_core/Cargo.toml, identity_iota_core/src/rebased/iota/well_known_networks.rs
Fixes dprint issue and add license header to get code aligned.
Ran against local validation steps.
=> Fix dprint issue and add license header

identity_iota_core/src/rebased/iota/well_known_networks.rs
Add package metadata for testnet.
=> Add testnet package metadata 

README.md, identity_iota/README.md
Use git dependencies and update private network instructions
=> Update readme includes

CHANGELOG.md
Add changelog entry for the `v1.6.0-alpha.1` version
=> Add `v1.6.0-alpha.1` changelog

README.md, identity_iota/README.md
=> Update rebased readme

README.md, identity_iota/README.md
Add Rebased banner to Stardust readme
=> Add Rebased banner for Stardust

.github/workflows/build-and-test.yml
Run `iota move test` to run `IotaIdentity` Move package tests
Closes issue #1465
=> test identity package in CI

bindings/wasm/examples/src/1_advanced/4_custom_resolution.ts, bindings/wasm/package-lock.json, bindings/wasm/package.json
Replace did-key dependency to makes test compatible with node >= `22`
Run CI
=> Replace did-key dependency to fix tests

bindings/wasm/identity_wasm/examples/src/1_advanced/4_custom_resolution.ts, bindings/wasm/identity_wasm/package-lock.json, bindings/wasm/identity_wasm/package.json
mirror of https://github.com/iotaledger/identity.rs/pull/1530
Replace did-key dependency to makes test compatible with node >= `22`
Run CI
=> Fix did key test rebased

bindings/wasm/identity_wasm/examples/src/0_basic/0_create_did.ts, bindings/wasm/identity_wasm/examples/src/0_basic/1_update_did.ts, bindings/wasm/identity_wasm/examples/src/0_basic/2_resolve_did.ts, bindings/wasm/identity_wasm/examples/src/0_basic/3_deactivate_did.ts, bindings/wasm/identity_wasm/examples/src/1_advanced/4_custom_resolution.ts
Aligns DID retrieval with Rust examples.
=> Update did fetching in wasm examples

.github/workflows/rust-deploy-docs.yml
Mirror of #1533 without the automatic trigger
Will be tested in CI
=> Add Rust deploy docs workflow

README.md, identity_iota/README.md
Link Rust docs deployed via #1540 
=> Add Rust docs link

.github/actions/iota-rebase-sandbox/setup/action.yml, README.md, bindings/grpc/Cargo.toml, examples/Cargo.toml, identity_iota/Cargo.toml, identity_iota/README.md, identity_iota_core/Cargo.toml, identity_iota_core/packages/iota_identity/Move.toml, identity_iota_core/tests/e2e/common.rs, identity_iota_interaction/Cargo.toml
Use latest testnet version of IOTA
CI passes
=> Bump iota version

.github/actions/publish/publish-wasm/action.yml, .github/workflows/interactions-publish-to-npm.yml
=> Add interaction release

.github/actions/rust/sccache/setup-sccache/action.yml
Fix outdated brew command
CI passes
=> Update brew update command

identity_iota_core/src/rebased/iota/well_known_networks.rs
Published the package to Testnet & Devnet, updating the corresponding hardcoded addresses.
=> Release `identity_iota` Move package to Testnet & Devnet

bindings/wasm/identity_wasm/package-lock.json, bindings/wasm/identity_wasm/package.json
Use published interaction package
CI passes
=> Use published interaction package

bindings/wasm/build/web.js
Fix hardcoded wasm binary name
Inspected artifacts locally
=> Fix interaction web build

bindings/wasm/iota_interaction_ts/lib/index.ts, bindings/wasm/iota_interaction_ts/src/asset_move_calls.rs, bindings/wasm/iota_interaction_ts/src/bindings/wasm_types.rs, bindings/wasm/iota_interaction_ts/src/migration_move_calls.rs
Rework interaction export to get rid of faulty "snippets"
CI passes, tested and inspected locally
=> Fix Interaction Wasm build

bindings/wasm/identity_wasm/Cargo.toml, bindings/wasm/identity_wasm/package-lock.json, bindings/wasm/identity_wasm/package.json, bindings/wasm/iota_interaction_ts/lib/index.ts, bindings/wasm/iota_interaction_ts/lib/tsconfig.json, bindings/wasm/iota_interaction_ts/lib/tsconfig.web.json, bindings/wasm/iota_interaction_ts/package-lock.json, bindings/wasm/iota_interaction_ts/package.json, bindings/wasm/iota_interaction_ts/tsconfig.json
=> Re-export interaction bindings

.github/workflows/upload-docs.yml, bindings/wasm/identity_wasm/tsconfig.typedoc.json, bindings/wasm/identity_wasm/typedoc.json
=> Exclude interaction docs, fix docs path

README.md, bindings/wasm/identity_wasm/README.md, bindings/wasm/identity_wasm/examples/README.md, examples/README.md, identity_credential/README.md, identity_iota/README.md, identity_iota_core/README.md
Harmonize example Readmes for Rust and Wasm
Replace Wiki links
=> Harmonize example Readmes, replace Wiki links

bindings/wasm/iota_interaction_ts/Cargo.toml, examples/Cargo.toml, identity_core/Cargo.toml, identity_credential/Cargo.toml, identity_did/Cargo.toml, identity_document/Cargo.toml, identity_ecdsa_verifier/Cargo.toml, identity_eddsa_verifier/Cargo.toml, identity_iota/Cargo.toml, identity_iota_core/Cargo.toml, identity_iota_interaction/Cargo.toml, identity_jose/Cargo.toml, identity_resolver/Cargo.toml, identity_storage/Cargo.toml, identity_stronghold/Cargo.toml, identity_verification/Cargo.toml
Bump rust versions to to reflect version in build docs
=> Bump rust versions

.github/workflows/shared-create-hotfix-pr.yml, .github/workflows/shared-create-main-release-pr.yml
Disable changelog generation as it breaks our release process.
=> Disable changelog generation

.github/workflows/build-and-test.yml, .github/workflows/shared-create-hotfix-pr.yml, .github/workflows/shared-create-main-release-pr.yml, CHANGELOG.md, bindings/wasm/identity_wasm/CHANGELOG.md, bindings/wasm/identity_wasm/src/credential/jpt_credential_validator/jpt_credential_validation_options.rs, bindings/wasm/identity_wasm/src/credential/jwt_credential_validation/jwt_credential_validator.rs, bindings/wasm/identity_wasm/src/credential/revocation/status_list_2021/credential.rs, bindings/wasm/identity_wasm/src/credential/revocation/validity_timeframe_2024/status.rs, bindings/wasm/identity_wasm/tests/storage.ts, identity_core/src/common/ordered_set.rs, identity_credential/src/domain_linkage/domain_linkage_validator.rs, identity_credential/src/domain_linkage/error.rs, identity_credential/src/presentation/jwt_serialization.rs, identity_credential/src/revocation/status_list_2021/status_list.rs, identity_credential/src/validator/jwt_credential_validation/error.rs, identity_credential/src/validator/sd_jwt/error.rs, identity_credential/src/validator/sd_jwt/validator.rs, identity_jose/src/error.rs, identity_storage/src/storage/tests/kb_jwt.rs, identity_stronghold/src/storage/mod.rs
Adds latest changes from main branch to alpha branch.
Checked build locally.
=> Add updates from `main` branch

.github/workflows/build-and-test.yml, .github/workflows/shared-create-hotfix-pr.yml, .github/workflows/shared-create-main-release-pr.yml, CHANGELOG.md, bindings/wasm/identity_wasm/CHANGELOG.md, bindings/wasm/identity_wasm/src/credential/jpt_credential_validator/jpt_credential_validation_options.rs, bindings/wasm/identity_wasm/src/credential/jwt_credential_validation/jwt_credential_validator.rs, bindings/wasm/identity_wasm/src/credential/revocation/status_list_2021/credential.rs, bindings/wasm/identity_wasm/src/credential/revocation/validity_timeframe_2024/status.rs, bindings/wasm/identity_wasm/tests/storage.ts, identity_core/src/common/ordered_set.rs, identity_credential/src/domain_linkage/domain_linkage_validator.rs, identity_credential/src/domain_linkage/error.rs, identity_credential/src/presentation/jwt_serialization.rs, identity_credential/src/revocation/status_list_2021/status_list.rs, identity_credential/src/validator/jwt_credential_validation/error.rs, identity_credential/src/validator/sd_jwt/error.rs, identity_credential/src/validator/sd_jwt/validator.rs, identity_jose/src/error.rs, identity_storage/src/storage/tests/kb_jwt.rs, identity_stronghold/src/storage/mod.rs
Adds latest changes from main branch to alpha branch.
Checked build locally.
=> Add updates from main

.github/workflows/deploy-move-package.yml, .gitignore
- Change script invocation
- Add `iota` folder created by the sandbox action to `.gitignore` to not interfere with automatic commits
Successful CI run [here](https://github.com/iotaledger/identity.rs/actions/runs/14703188069)
=> Fix script action

.github/actions/iota-rebase-sandbox/load-keytool/action.yml, identity_iota_core/packages/iota_identity/Move.lock, identity_iota_core/src/rebased/iota/well_known_networks.rs
Release IotaIdentity on Mainnet.
=> Release IotaIdentity package on Mainnet

bindings/wasm/identity_wasm/Cargo.toml, examples/Cargo.toml, identity_core/Cargo.toml, identity_credential/Cargo.toml, identity_did/Cargo.toml, identity_document/Cargo.toml, identity_ecdsa_verifier/Cargo.toml, identity_eddsa_verifier/Cargo.toml, identity_iota/Cargo.toml, identity_iota_core/Cargo.toml, identity_jose/Cargo.toml, identity_resolver/Cargo.toml, identity_storage/Cargo.toml, identity_stronghold/Cargo.toml, identity_verification/Cargo.toml
Bump package version to 1.6.0-beta
=> Bump package version to 1.6.0-beta

bindings/grpc/README.md, identity_credential/src/domain_linkage/domain_linkage_configuration.rs, identity_credential/src/validator/jwt_credential_validation/error.rs, identity_iota_core/src/rebased/utils.rs, identity_jose/src/jws/encoding/encoder.rs
=> chore: remove redundant words

.github/workflows/build-and-test.yml
set git `longpaths` config to allow path > 260 chars
Fixes issues like [this](https://github.com/iotaledger/identity/actions/runs/17282277764/job/49052919374)
CI passes
=> Fix windows longpaths

identity_credential/src/sd_jwt_vc/presentation.rs, identity_credential/src/sd_jwt_vc/tests/mod.rs, identity_credential/src/sd_jwt_vc/tests/presentation.rs
Fixes a bug that made `SdJwtVcPresentationBuilder::conceal` not working properly.
=> Fix `SdJwtVcPresentationBuilder::conceal`

.github/workflows/clippy.yml, .github/workflows/shared-build-wasm.yml, bindings/wasm/identity_wasm/Cargo.toml
Use pinned version wasm-bindgen v0.2.102
=> Pin wasm-bindgen to v0.2.102

bindings/wasm/identity_wasm/Cargo.toml, bindings/wasm/identity_wasm/package-lock.json, bindings/wasm/identity_wasm/package.json
Bump identity WASM to v1.6.0-beta.10
=> Bump identity WASM to 1.6.0-beta.10
